#1. Neural News Recommendation with Multi-Head Self Attention Model (NRMS)

NRMS models user interest by learning semantic representations of news articles and capturing relationships among previously clicked news in user history via multi-head self-attention. The model consists of a news encoder, a user encoder, and an MLP-based prediction layer.

The model comprises the following components:
- **`NewsEncoder`**: The news encoder comprises two submodules, whose outputs are fused through a fully connected layer to produce a unified news representation vector, which is included inside MLP used in Model 2.
    - `TextNewsEncoder`: This component processes textual features derived from concatenated title_abstract BERT embeddings, together with categorical features such as subcluster categories, which are encoded via learnable embeddings
    - `EntityNewsEncoder`: This component incorporates additional semantic knowledge by leveraging on entity-based representations, such as knowledge graph and named entity embeddings extracted from news content

- **`UserEncoder`**: The user encoder models user preferences by aggregating representations of previously clicked news articles. Each clicked news article is first encoded using the shared NewsEncoder to obtain dense vector representations. These representations are then further processed to capture relationships among the clicked news and produce a unified user representation

   - **Self-Attention Block**: This component applies multi-head self-attention to model interactions among clicked news articles, enabling the encoder to capture contextual relationships within the users' browsing history, which is included inside MLP used in Model 2
   - **Additive Attention**: This component aggregates the attended news representations into a single user vector by assigning higher weights to more relevant or informative clicked articles
   - Default User Embedding: For users without an available history (cold start users), a learnable default embedding is used to represent user preferences.
- **MLP-based Prediction layer**: The final user representation and candidate news representation are passed into the MLP alongside other User Features, News Features and context features. This component is based on Model 2, but incorporates attention.

##1.1 Load Packages

In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import os
import ast
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
import torch.nn.functional as F
from tqdm import tqdm
from sklearn.metrics import roc_auc_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##1.2 Load Processed News Dataset

In [ ]:
# Load entity embeddings
news_ent_path = '/content/drive/MyDrive/data/news/news_entities.parquet'
news_entities = pd.read_parquet(news_ent_path)

In [ ]:
news_entities.head()

,news_id,kg_title_emb,kg_abstract_emb,kg_title_flag,kg_abstract_flag,ner_title_emb,ner_abstract_emb,ner_title_flag,ner_abstract_flag
0,N55528,"[0.008122858, -0.07991525, -0.016764905, 0.158...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,0,"[-0.025332777, 0.07448415, 0.046060078, 0.0411...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,0
1,N19639,"[-0.029497119, -0.021168852, 0.03713986, -0.11...","[-0.029497119, -0.021168852, 0.03713986, -0.11...",1,1,"[-0.007022121, 0.08226046, -0.035310447, 0.089...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,0
2,N61837,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-0.06553931, -0.08845358, -0.015253108, -0.03...",0,1,"[-0.07378371, 0.10624181, 0.00063977536, 0.055...","[0.016665561, 0.026591385, -0.07544741, 0.0324...",1,1
3,N53526,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0061505293, -0.10125916, -0.060772542, 0.04...",0,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-0.008782822, 0.051812273, -0.033509996, -0.0...",0,1
4,N38324,"[0.045086294, 0.05803315, 0.016441302, 0.00560...","[-0.02720732, -0.0005318837, 0.08588548, -0.13...",1,1,"[-0.0391243, 0.029080106, 0.014465057, 0.06514...","[-0.0037145745, -0.02635876, -0.027976032, 0.0...",1,1

In [ ]:
# Load news features dataset
news_features_path = '/content/drive/MyDrive/features/news_features/news_features.parquet'
news_features = pd.read_parquet(news_features_path)

In [ ]:
news_features.head()

,news_id,subclustered_category,bert_emb_0,bert_emb_1,bert_emb_2,bert_emb_3,bert_emb_4,bert_emb_5,bert_emb_6,bert_emb_7,...,topic_41,topic_42,topic_43,topic_44,topic_45,topic_46,topic_47,topic_48,topic_49,ctr_norm
0,26629,lifestyleroyals,-0.006567,0.030011,0.041711,0.008560,0.023631,0.013891,0.019353,-0.043506,...,0.000317,0.004183,-0.003760,0.011950,0.000253,-0.007036,-0.005527,0.003258,0.003991,-0.153225
1,45241,weightloss,0.013164,0.027189,0.018828,0.059265,-0.004955,-0.021681,0.014436,0.000486,...,-0.012257,0.007741,0.002588,0.003268,0.035718,0.015612,0.039606,0.018964,-0.044307,-0.153225
2,49591,CounterTerrorism_MiddleEastConflict,-0.018924,0.047626,0.033783,0.046084,0.001255,-0.003395,-0.018784,0.022281,...,0.000855,-0.005659,-0.012527,0.017737,0.015317,0.026903,-0.008147,0.028906,-0.035933,-0.153225
3,28765,health_general,0.047500,0.066250,0.007197,0.021490,-0.008358,0.053810,0.050125,0.025326,...,0.010095,-0.017281,0.006360,-0.008582,-0.017680,-0.003062,-0.004098,0.015898,0.013547,-0.153225
4,28005,medical,0.000916,0.073814,-0.011449,0.011641,0.016896,-0.063047,0.051980,0.021564,...,0.006993,0.005708,0.006243,0.000269,0.003198,0.005175,0.004035,-0.003169,0.005123,-0.153225

In [ ]:
news_features.columns.tolist()

['news_id',
 'subclustered_category',
 'bert_emb_0',
 'bert_emb_1',
 'bert_emb_2',
 'bert_emb_3',
 'bert_emb_4',
 'bert_emb_5',
 'bert_emb_6',
 'bert_emb_7',
 'bert_emb_8',
 'bert_emb_9',
 'bert_emb_10',
 'bert_emb_11',
 'bert_emb_12',
 'bert_emb_13',
 'bert_emb_14',
 'bert_emb_15',
 'bert_emb_16',
 'bert_emb_17',
 'bert_emb_18',
 'bert_emb_19',
 'bert_emb_20',
 'bert_emb_21',
 'bert_emb_22',
 'bert_emb_23',
 'bert_emb_24',
 'bert_emb_25',
 'bert_emb_26',
 'bert_emb_27',
 'bert_emb_28',
 'bert_emb_29',
 'bert_emb_30',
 'bert_emb_31',
 'bert_emb_32',
 'bert_emb_33',
 'bert_emb_34',
 'bert_emb_35',
 'bert_emb_36',
 'bert_emb_37',
 'bert_emb_38',
 'bert_emb_39',
 'bert_emb_40',
 'bert_emb_41',
 'bert_emb_42',
 'bert_emb_43',
 'bert_emb_44',
 'bert_emb_45',
 'bert_emb_46',
 'bert_emb_47',
 'bert_emb_48',
 'bert_emb_49',
 'bert_emb_50',
 'bert_emb_51',
 'bert_emb_52',
 'bert_emb_53',
 'bert_emb_54',
 'bert_emb_55',
 'bert_emb_56',
 'bert_emb_57',
 'bert_emb_58',
 'bert_emb_59',
 'bert_emb_60',
 'bert_emb_61',
 'bert_emb_62',
 'bert_emb_63',
 'bert_emb_64',
 'bert_emb_65',
 'bert_emb_66',
 'bert_emb_67',
 'bert_emb_68',
 'bert_emb_69',
 'bert_emb_70',
 'bert_emb_71',
 'bert_emb_72',
 'bert_emb_73',
 'bert_emb_74',
 'bert_emb_75',
 'bert_emb_76',
 'bert_emb_77',
 'bert_emb_78',
 'bert_emb_79',
 'bert_emb_80',
 'bert_emb_81',
 'bert_emb_82',
 'bert_emb_83',
 'bert_emb_84',
 'bert_emb_85',
 'bert_emb_86',
 'bert_emb_87',
 'bert_emb_88',
 'bert_emb_89',
 'bert_emb_90',
 'bert_emb_91',
 'bert_emb_92',
 'bert_emb_93',
 'bert_emb_94',
 'bert_emb_95',
 'bert_emb_96',
 'bert_emb_97',
 'bert_emb_98',
 'bert_emb_99',
 'bert_emb_100',
 'bert_emb_101',
 'bert_emb_102',
 'bert_emb_103',
 'bert_emb_104',
 'bert_emb_105',
 'bert_emb_106',
 'bert_emb_107',
 'bert_emb_108',
 'bert_emb_109',
 'bert_emb_110',
 'bert_emb_111',
 'bert_emb_112',
 'bert_emb_113',
 'bert_emb_114',
 'bert_emb_115',
 'bert_emb_116',
 'bert_emb_117',
 'bert_emb_118',
 'bert_emb_119',
 'bert_emb_120',
 'bert_emb_121',
 'bert_emb_122',
 'bert_emb_123',
 'bert_emb_124',
 'bert_emb_125',
 'bert_emb_126',
 'bert_emb_127',
 'bert_emb_128',
 'bert_emb_129',
 'bert_emb_130',
 'bert_emb_131',
 'bert_emb_132',
 'bert_emb_133',
 'bert_emb_134',
 'bert_emb_135',
 'bert_emb_136',
 'bert_emb_137',
 'bert_emb_138',
 'bert_emb_139',
 'bert_emb_140',
 'bert_emb_141',
 'bert_emb_142',
 'bert_emb_143',
 'bert_emb_144',
 'bert_emb_145',
 'bert_emb_146',
 'bert_emb_147',
 'bert_emb_148',
 'bert_emb_149',
 'bert_emb_150',
 'bert_emb_151',
 'bert_emb_152',
 'bert_emb_153',
 'bert_emb_154',
 'bert_emb_155',
 'bert_emb_156',
 'bert_emb_157',
 'bert_emb_158',
 'bert_emb_159',
 'bert_emb_160',
 'bert_emb_161',
 'bert_emb_162',
 'bert_emb_163',
 'bert_emb_164',
 'bert_emb_165',
 'bert_emb_166',
 'bert_emb_167',
 'bert_emb_168',
 'bert_emb_169',
 'bert_emb_170',
 'bert_emb_171',
 'bert_emb_172',
 'bert_emb_173',
 'bert_emb_174',
 'bert_emb_175',
 'bert_emb_176',
 'bert_emb_177',
 'bert_emb_178',
 'bert_emb_179',
 'bert_emb_180',
 'bert_emb_181',
 'bert_emb_182',
 'bert_emb_183',
 'bert_emb_184',
 'bert_emb_185',
 'bert_emb_186',
 'bert_emb_187',
 'bert_emb_188',
 'bert_emb_189',
 'bert_emb_190',
 'bert_emb_191',
 'bert_emb_192',
 'bert_emb_193',
 'bert_emb_194',
 'bert_emb_195',
 'bert_emb_196',
 'bert_emb_197',
 'bert_emb_198',
 'bert_emb_199',
 'bert_emb_200',
 'bert_emb_201',
 'bert_emb_202',
 'bert_emb_203',
 'bert_emb_204',
 'bert_emb_205',
 'bert_emb_206',
 'bert_emb_207',
 'bert_emb_208',
 'bert_emb_209',
 'bert_emb_210',
 'bert_emb_211',
 'bert_emb_212',
 'bert_emb_213',
 'bert_emb_214',
 'bert_emb_215',
 'bert_emb_216',
 'bert_emb_217',
 'bert_emb_218',
 'bert_emb_219',
 'bert_emb_220',
 'bert_emb_221',
 'bert_emb_222',
 'bert_emb_223',
 'bert_emb_224',
 'bert_emb_225',
 'bert_emb_226',
 'bert_emb_227',
 'bert_emb_228',
 'bert_emb_229',
 'bert_emb_230',
 'bert_emb_231',
 'bert_emb_232',
 'bert_emb_233',
 'bert_emb_234',
 'bert_emb_235',
 'bert_emb_236',
 'bert_emb_237',
 'bert_emb_238',
 'bert_emb_239',
 'bert_emb_240',
 'bert_emb_241',
 'bert_emb_242',
 'bert_emb_243',
 'bert_emb_244',
 'bert_emb_245',
 'bert_emb_246',
 'bert_emb_247',
 'bert_emb_248',
 'bert_emb_249',
 'bert_emb_250',
 'bert_emb_251',
 'bert_emb_252',
 'bert_emb_253',
 'bert_emb_254',
 'bert_emb_255',
 'bert_emb_256',
 'bert_emb_257',
 'bert_emb_258',
 'bert_emb_259',
 'bert_emb_260',
 'bert_emb_261',
 'bert_emb_262',
 'bert_emb_263',
 'bert_emb_264',
 'bert_emb_265',
 'bert_emb_266',
 'bert_emb_267',
 'bert_emb_268',
 'bert_emb_269',
 'bert_emb_270',
 'bert_emb_271',
 'bert_emb_272',
 'bert_emb_273',
 'bert_emb_274',
 'bert_emb_275',
 'bert_emb_276',
 'bert_emb_277',
 'bert_emb_278',
 'bert_emb_279',
 'bert_emb_280',
 'bert_emb_281',
 'bert_emb_282',
 'bert_emb_283',
 'bert_emb_284',
 'bert_emb_285',
 'bert_emb_286',
 'bert_emb_287',
 'bert_emb_288',
 'bert_emb_289',
 'bert_emb_290',
 'bert_emb_291',
 'bert_emb_292',
 'bert_emb_293',
 'bert_emb_294',
 'bert_emb_295',
 'bert_emb_296',
 'bert_emb_297',
 'bert_emb_298',
 'bert_emb_299',
 'bert_emb_300',
 'bert_emb_301',
 'bert_emb_302',
 'bert_emb_303',
 'bert_emb_304',
 'bert_emb_305',
 'bert_emb_306',
 'bert_emb_307',
 'bert_emb_308',
 'bert_emb_309',
 'bert_emb_310',
 'bert_emb_311',
 'bert_emb_312',
 'bert_emb_313',
 'bert_emb_314',
 'bert_emb_315',
 'bert_emb_316',
 'bert_emb_317',
 'bert_emb_318',
 'bert_emb_319',
 'bert_emb_320',
 'bert_emb_321',
 'bert_emb_322',
 'bert_emb_323',
 'bert_emb_324',
 'bert_emb_325',
 'bert_emb_326',
 'bert_emb_327',
 'bert_emb_328',
 'bert_emb_329',
 'bert_emb_330',
 'bert_emb_331',
 'bert_emb_332',
 'bert_emb_333',
 'bert_emb_334',
 'bert_emb_335',
 'bert_emb_336',
 'bert_emb_337',
 'bert_emb_338',
 'bert_emb_339',
 'bert_emb_340',
 'bert_emb_341',
 'bert_emb_342',
 'bert_emb_343',
 'bert_emb_344',
 'bert_emb_345',
 'bert_emb_346',
 'bert_emb_347',
 'bert_emb_348',
 'bert_emb_349',
 'bert_emb_350',
 'bert_emb_351',
 'bert_emb_352',
 'bert_emb_353',
 'bert_emb_354',
 'bert_emb_355',
 'bert_emb_356',
 'bert_emb_357',
 'bert_emb_358',
 'bert_emb_359',
 'bert_emb_360',
 'bert_emb_361',
 'bert_emb_362',
 'bert_emb_363',
 'bert_emb_364',
 'bert_emb_365',
 'bert_emb_366',
 'bert_emb_367',
 'bert_emb_368',
 'bert_emb_369',
 'bert_emb_370',
 'bert_emb_371',
 'bert_emb_372',
 'bert_emb_373',
 'bert_emb_374',
 'bert_emb_375',
 'bert_emb_376',
 'bert_emb_377',
 'bert_emb_378',
 'bert_emb_379',
 'bert_emb_380',
 'bert_emb_381',
 'bert_emb_382',
 'bert_emb_383',
 'bert_emb_384',
 'bert_emb_385',
 'bert_emb_386',
 'bert_emb_387',
 'bert_emb_388',
 'bert_emb_389',
 'bert_emb_390',
 'bert_emb_391',
 'bert_emb_392',
 'bert_emb_393',
 'bert_emb_394',
 'bert_emb_395',
 'bert_emb_396',
 'bert_emb_397',
 'bert_emb_398',
 'bert_emb_399',
 'bert_emb_400',
 'bert_emb_401',
 'bert_emb_402',
 'bert_emb_403',
 'bert_emb_404',
 'bert_emb_405',
 'bert_emb_406',
 'bert_emb_407',
 'bert_emb_408',
 'bert_emb_409',
 'bert_emb_410',
 'bert_emb_411',
 'bert_emb_412',
 'bert_emb_413',
 'bert_emb_414',
 'bert_emb_415',
 'bert_emb_416',
 'bert_emb_417',
 'bert_emb_418',
 'bert_emb_419',
 'bert_emb_420',
 'bert_emb_421',
 'bert_emb_422',
 'bert_emb_423',
 'bert_emb_424',
 'bert_emb_425',
 'bert_emb_426',
 'bert_emb_427',
 'bert_emb_428',
 'bert_emb_429',
 'bert_emb_430',
 'bert_emb_431',
 'bert_emb_432',
 'bert_emb_433',
 'bert_emb_434',
 'bert_emb_435',
 'bert_emb_436',
 'bert_emb_437',
 'bert_emb_438',
 'bert_emb_439',
 'bert_emb_440',
 'bert_emb_441',
 'bert_emb_442',
 'bert_emb_443',
 'bert_emb_444',
 'bert_emb_445',
 'bert_emb_446',
 'bert_emb_447',
 'bert_emb_448',
 'bert_emb_449',
 'bert_emb_450',
 'bert_emb_451',
 'bert_emb_452',
 'bert_emb_453',
 'bert_emb_454',
 'bert_emb_455',
 'bert_emb_456',
 'bert_emb_457',
 'bert_emb_458',
 'bert_emb_459',
 'bert_emb_460',
 'bert_emb_461',
 'bert_emb_462',
 'bert_emb_463',
 'bert_emb_464',
 'bert_emb_465',
 'bert_emb_466',
 'bert_emb_467',
 'bert_emb_468',
 'bert_emb_469',
 'bert_emb_470',
 'bert_emb_471',
 'bert_emb_472',
 'bert_emb_473',
 'bert_emb_474',
 'bert_emb_475',
 'bert_emb_476',
 'bert_emb_477',
 'bert_emb_478',
 'bert_emb_479',
 'bert_emb_480',
 'bert_emb_481',
 'bert_emb_482',
 'bert_emb_483',
 'bert_emb_484',
 'bert_emb_485',
 'bert_emb_486',
 'bert_emb_487',
 'bert_emb_488',
 'bert_emb_489',
 'bert_emb_490',
 'bert_emb_491',
 'bert_emb_492',
 'bert_emb_493',
 'bert_emb_494',
 'bert_emb_495',
 'bert_emb_496',
 'bert_emb_497',
 'bert_emb_498',
 'bert_emb_499',
 'bert_emb_500',
 'bert_emb_501',
 'bert_emb_502',
 'bert_emb_503',
 'bert_emb_504',
 'bert_emb_505',
 'bert_emb_506',
 'bert_emb_507',
 'bert_emb_508',
 'bert_emb_509',
 'bert_emb_510',
 'bert_emb_511',
 'bert_emb_512',
 'bert_emb_513',
 'bert_emb_514',
 'bert_emb_515',
 'bert_emb_516',
 'bert_emb_517',
 'bert_emb_518',
 'bert_emb_519',
 'bert_emb_520',
 'bert_emb_521',
 'bert_emb_522',
 'bert_emb_523',
 'bert_emb_524',
 'bert_emb_525',
 'bert_emb_526',
 'bert_emb_527',
 'bert_emb_528',
 'bert_emb_529',
 'bert_emb_530',
 'bert_emb_531',
 'bert_emb_532',
 'bert_emb_533',
 'bert_emb_534',
 'bert_emb_535',
 'bert_emb_536',
 'bert_emb_537',
 'bert_emb_538',
 'bert_emb_539',
 'bert_emb_540',
 'bert_emb_541',
 'bert_emb_542',
 'bert_emb_543',
 'bert_emb_544',
 'bert_emb_545',
 'bert_emb_546',
 'bert_emb_547',
 'bert_emb_548',
 'bert_emb_549',
 'bert_emb_550',
 'bert_emb_551',
 'bert_emb_552',
 'bert_emb_553',
 'bert_emb_554',
 'bert_emb_555',
 'bert_emb_556',
 'bert_emb_557',
 'bert_emb_558',
 'bert_emb_559',
 'bert_emb_560',
 'bert_emb_561',
 'bert_emb_562',
 'bert_emb_563',
 'bert_emb_564',
 'bert_emb_565',
 'bert_emb_566',
 'bert_emb_567',
 'bert_emb_568',
 'bert_emb_569',
 'bert_emb_570',
 'bert_emb_571',
 'bert_emb_572',
 'bert_emb_573',
 'bert_emb_574',
 'bert_emb_575',
 'bert_emb_576',
 'bert_emb_577',
 'bert_emb_578',
 'bert_emb_579',
 'bert_emb_580',
 'bert_emb_581',
 'bert_emb_582',
 'bert_emb_583',
 'bert_emb_584',
 'bert_emb_585',
 'bert_emb_586',
 'bert_emb_587',
 'bert_emb_588',
 'bert_emb_589',
 'bert_emb_590',
 'bert_emb_591',
 'bert_emb_592',
 'bert_emb_593',
 'bert_emb_594',
 'bert_emb_595',
 'bert_emb_596',
 'bert_emb_597',
 'bert_emb_598',
 'bert_emb_599',
 'bert_emb_600',
 'bert_emb_601',
 'bert_emb_602',
 'bert_emb_603',
 'bert_emb_604',
 'bert_emb_605',
 'bert_emb_606',
 'bert_emb_607',
 'bert_emb_608',
 'bert_emb_609',
 'bert_emb_610',
 'bert_emb_611',
 'bert_emb_612',
 'bert_emb_613',
 'bert_emb_614',
 'bert_emb_615',
 'bert_emb_616',
 'bert_emb_617',
 'bert_emb_618',
 'bert_emb_619',
 'bert_emb_620',
 'bert_emb_621',
 'bert_emb_622',
 'bert_emb_623',
 'bert_emb_624',
 'bert_emb_625',
 'bert_emb_626',
 'bert_emb_627',
 'bert_emb_628',
 'bert_emb_629',
 'bert_emb_630',
 'bert_emb_631',
 'bert_emb_632',
 'bert_emb_633',
 'bert_emb_634',
 'bert_emb_635',
 'bert_emb_636',
 'bert_emb_637',
 'bert_emb_638',
 'bert_emb_639',
 'bert_emb_640',
 'bert_emb_641',
 'bert_emb_642',
 'bert_emb_643',
 'bert_emb_644',
 'bert_emb_645',
 'bert_emb_646',
 'bert_emb_647',
 'bert_emb_648',
 'bert_emb_649',
 'bert_emb_650',
 'bert_emb_651',
 'bert_emb_652',
 'bert_emb_653',
 'bert_emb_654',
 'bert_emb_655',
 'bert_emb_656',
 'bert_emb_657',
 'bert_emb_658',
 'bert_emb_659',
 'bert_emb_660',
 'bert_emb_661',
 'bert_emb_662',
 'bert_emb_663',
 'bert_emb_664',
 'bert_emb_665',
 'bert_emb_666',
 'bert_emb_667',
 'bert_emb_668',
 'bert_emb_669',
 'bert_emb_670',
 'bert_emb_671',
 'bert_emb_672',
 'bert_emb_673',
 'bert_emb_674',
 'bert_emb_675',
 'bert_emb_676',
 'bert_emb_677',
 'bert_emb_678',
 'bert_emb_679',
 'bert_emb_680',
 'bert_emb_681',
 'bert_emb_682',
 'bert_emb_683',
 'bert_emb_684',
 'bert_emb_685',
 'bert_emb_686',
 'bert_emb_687',
 'bert_emb_688',
 'bert_emb_689',
 'bert_emb_690',
 'bert_emb_691',
 'bert_emb_692',
 'bert_emb_693',
 'bert_emb_694',
 'bert_emb_695',
 'bert_emb_696',
 'bert_emb_697',
 'bert_emb_698',
 'bert_emb_699',
 'bert_emb_700',
 'bert_emb_701',
 'bert_emb_702',
 'bert_emb_703',
 'bert_emb_704',
 'bert_emb_705',
 'bert_emb_706',
 'bert_emb_707',
 'bert_emb_708',
 'bert_emb_709',
 'bert_emb_710',
 'bert_emb_711',
 'bert_emb_712',
 'bert_emb_713',
 'bert_emb_714',
 'bert_emb_715',
 'bert_emb_716',
 'bert_emb_717',
 'bert_emb_718',
 'bert_emb_719',
 'bert_emb_720',
 'bert_emb_721',
 'bert_emb_722',
 'bert_emb_723',
 'bert_emb_724',
 'bert_emb_725',
 'bert_emb_726',
 'bert_emb_727',
 'bert_emb_728',
 'bert_emb_729',
 'bert_emb_730',
 'bert_emb_731',
 'bert_emb_732',
 'bert_emb_733',
 'bert_emb_734',
 'bert_emb_735',
 'bert_emb_736',
 'bert_emb_737',
 'bert_emb_738',
 'bert_emb_739',
 'bert_emb_740',
 'bert_emb_741',
 'bert_emb_742',
 'bert_emb_743',
 'bert_emb_744',
 'bert_emb_745',
 'bert_emb_746',
 'bert_emb_747',
 'bert_emb_748',
 'bert_emb_749',
 'bert_emb_750',
 'bert_emb_751',
 'bert_emb_752',
 'bert_emb_753',
 'bert_emb_754',
 'bert_emb_755',
 'bert_emb_756',
 'bert_emb_757',
 'bert_emb_758',
 'bert_emb_759',
 'bert_emb_760',
 'bert_emb_761',
 'bert_emb_762',
 'bert_emb_763',
 'bert_emb_764',
 'bert_emb_765',
 'bert_emb_766',
 'bert_emb_767',
 'topic_0',
 'topic_1',
 'topic_2',
 'topic_3',
 'topic_4',
 'topic_5',
 'topic_6',
 'topic_7',
 'topic_8',
 'topic_9',
 'topic_10',
 'topic_11',
 'topic_12',
 'topic_13',
 'topic_14',
 'topic_15',
 'topic_16',
 'topic_17',
 'topic_18',
 'topic_19',
 'topic_20',
 'topic_21',
 'topic_22',
 'topic_23',
 'topic_24',
 'topic_25',
 'topic_26',
 'topic_27',
 'topic_28',
 'topic_29',
 'topic_30',
 'topic_31',
 'topic_32',
 'topic_33',
 'topic_34',
 'topic_35',
 'topic_36',
 'topic_37',
 'topic_38',
 'topic_39',
 'topic_40',
 'topic_41',
 'topic_42',
 'topic_43',
 'topic_44',
 'topic_45',
 'topic_46',
 'topic_47',
 'topic_48',
 'topic_49',
 'ctr_norm']

##1.3 Load in User Dataset

In [ ]:
train = pd.read_parquet('/content/drive/MyDrive/data/train.parquet')
val= pd.read_parquet('/content/drive/MyDrive/data/val.parquet')
test = pd.read_parquet('/content/drive/MyDrive/data/test.parquet')

In [ ]:
# Load user features datasets
user_path = '/content/drive/MyDrive/features/user_features'
train_user_features = pd.read_parquet(f'{user_path}/train_user_features.parquet')
val_user_features = pd.read_parquet(f'{user_path}/val_user_features.parquet')
test_user_features = pd.read_parquet(f'{user_path}/test_user_features.parquet')

##1.4 Load in Interactions Dataset

In [ ]:
train_interaction_path = '/content/drive/MyDrive/features/interaction_features/train_interactions.parquet'
train_interactions = pd.read_parquet(train_interaction_path)
val_interaction_path = '/content/drive/MyDrive/features/interaction_features/val_interactions.parquet'
val_interactions = pd.read_parquet(val_interaction_path)
test_interaction_path = '/content/drive/MyDrive/features/interaction_features/test_interactions.parquet'
test_interactions = pd.read_parquet(test_interaction_path)

##1.5 Load in Context Dataset

In [ ]:
context_path = '/content/drive/MyDrive/features/context_features'
train_context_features = pd.read_parquet(f'{context_path}/train_context.parquet')
val_context_features = pd.read_parquet(f'{context_path}/val_context.parquet')
test_context_features = pd.read_parquet(f'{context_path}/test_context.parquet')

#2. News Encoder

News Encoder consists of two parallel news encoding branches:
1.   Text News Encoder captures semantic information from the title and abstract embeddings
2.   Entity News Encoder captures knowledge-level information from entity embeddings derived from a knowledge graph

The outputs of the Text News Encoder and Entity News Encoder are then concatenated and passed through a fusion layer to produce a unified news representation.

##2.1 Text News Encoder

`TextNewsEncoder` combines two sources of information for each new articles
1. A dense BERT emebdding derived from the concatenated title and abstract
2. A learnable embedding representing each subcluster category

Both vectors are projected into a shared 128-dimensional space and treated as a two-token sequence, where a multi-head self-attentioin layer models interactions between semantic content and categorical structure.

The contextualised tokens are then pooled and passed through a feedforward layer to produce the final 128-dimensional text representation.

In [ ]:
#Make the title_abs_matrix
bert_cols = [col for col in news_features.columns if col.startswith("bert_emb_")]
title_abs_matrix = np.stack(news_features[bert_cols].values)
title_abs_embedding_tensor = torch.from_numpy(title_abs_matrix)

In [ ]:
title_abs_matrix.shape

(51282, 768)

In [ ]:
# 1. Get unique non-null clusters
unique_clusters = news_features["subclustered_category"].dropna().unique()

# 2. Build mapping
cluster2id = {c: i for i, c in enumerate(unique_clusters)}

# 3. Add unknown cluster id
unknown_cluster_id = len(cluster2id)

# 4. Map + fill missing
news_features["subcluster_id"] = (
    news_features["subclustered_category"]
    .map(cluster2id)
    .fillna(unknown_cluster_id)
    .astype(int)
)

# 5. Convert to tensor
subcluster_id_tensor = torch.tensor(
    news_features["subcluster_id"].values,
    dtype=torch.long
)

subcluster_id_tensor.shape

torch.Size([51282])

In [ ]:
num_subclusters = len(unique_clusters) + 1
print(f"Number of subclusters: {num_subclusters}")

Number of subclusters: 96

In [ ]:
class TextNewsEncoder(nn.Module):
    def __init__(self, input_dim, num_subclusters, model_dim=128, num_heads=2, dropout=0.3):
        super().__init__()

        self.subcluster_embeddings = nn.Embedding(num_subclusters, 32)
        self.subcluster_proj = nn.Linear(32, model_dim) # New projection for subcluster embeddings

        # Project main text embedding to same dimension (d_model = 128)
        self.proj = nn.Linear(input_dim, model_dim)

        # Multi-head attention (batch_first=True is important)
        self.attention = nn.MultiheadAttention(
            embed_dim=model_dim,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True
        )

        # Feedforward layer to improve representation
        self.ffn = nn.Sequential(
            nn.Linear(model_dim, model_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

    def forward(self, title_abs_emb, subcluster_ids):
        """
        Inputs:
            title_abs_emb:   [batch, input_dim] (e.g., BERT embedding)
            subcluster_ids:  [batch] (integer IDs for subclusters)

        Output:
            text_vec: [batch, 128]
        """
        # 1. Project title_abs_emb to model_dim
        t = self.proj(title_abs_emb)      # [batch, 128]

        # 2. Look up subcluster embedding and project to model_dim
        s_emb_32 = self.subcluster_embeddings(subcluster_ids) # [batch, 32]

        s = self.subcluster_proj(s_emb_32)                     # [batch, 128]

        # 3. Stack into a 2-token sequence
        x = torch.stack([t, s], dim=1)    # [batch, 2, 128]

        # 4. Self-attention
        attn_output, _ = self.attention(x, x, x)

        # 5. Mean pooling over the 2 tokens
        pooled = attn_output.mean(dim=1)  # [batch, 128]

        # 6. Feedforward
        text_vec = self.ffn(pooled)

        return text_vec

##2.2 Entity News Encoder

`EntityEncoder` integrates four entity-level signals for each news article:
1. KG-based title embeddings
2. KG-based abstract embeddings
3. NER-based title embeddings
4. NER-based abstract embeddings

Each vector is projected into a shared 128-dimensional space and treated as a four-token sequence. There are also binary flags indicating whether each signal is present.

A multi-head self-attention layer models interactions among the available KG and NER tokens while masking out missing ones. The contextualized tokens are then pooled over valid positions and passed through a feedforward layer to produce the final 128‑dimensional entity representation.

In [ ]:
# Each branch embeddings stacked to form embedding matrix
kg_title_matrix = np.stack(news_entities["kg_title_emb"].values)
kg_abstract_matrix = np.stack(news_entities["kg_abstract_emb"].values)
ner_title_matrix = np.stack(news_entities["ner_title_emb"].values)
ner_abstract_matrix = np.stack(news_entities["ner_abstract_emb"].values)
flags_matrix = news_entities[
    ["kg_title_flag", "kg_abstract_flag", "ner_title_flag", "ner_abstract_flag"]
].values.astype(np.float32)

kg_title_tensor = torch.tensor(kg_title_matrix, dtype=torch.float32)
kg_abstract_tensor = torch.tensor(kg_abstract_matrix, dtype=torch.float32)
ner_title_tensor = torch.tensor(ner_title_matrix, dtype=torch.float32)
ner_abstract_tensor = torch.tensor(ner_abstract_matrix, dtype=torch.float32)
flags_tensor = torch.tensor(flags_matrix, dtype=torch.float32)

In [ ]:
class EntityEncoder(nn.Module):
    def __init__(
        self,
        kg_input_dim=100,
        ner_input_dim=384,
        model_dim=128,
        num_heads=2,
        dropout=0.3
    ):
        super().__init__()

        self.kg_proj = nn.Linear(kg_input_dim, model_dim)
        self.ner_proj = nn.Linear(ner_input_dim, model_dim)

        self.attention = nn.MultiheadAttention(
            embed_dim=model_dim,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True
        )

        self.ffn = nn.Sequential(
            nn.Linear(model_dim, model_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

    def forward(
        self,
        kg_title_emb,
        kg_abstract_emb,
        ner_title_emb,
        ner_abstract_emb,
        kg_title_flag,
        kg_abstract_flag,
        ner_title_flag,
        ner_abstract_flag
    ):
        kg_title_proj = self.kg_proj(kg_title_emb)
        kg_abstract_proj = self.kg_proj(kg_abstract_emb)
        ner_title_proj = self.ner_proj(ner_title_emb)
        ner_abstract_proj = self.ner_proj(ner_abstract_emb)

        x = torch.stack([
            kg_title_proj,
            kg_abstract_proj,
            ner_title_proj,
            ner_abstract_proj
        ], dim=1)   # [B, 4, 128]

        flags = torch.stack([
            kg_title_flag,
            kg_abstract_flag,
            ner_title_flag,
            ner_abstract_flag
        ], dim=1)

        key_padding_mask = (flags == 0)   # [B, 4]
        all_masked = key_padding_mask.all(dim=1)  # [B]

        # avoid passing fully-masked rows into attention
        safe_key_padding_mask = key_padding_mask.clone()
        safe_key_padding_mask[all_masked] = False

        attn_output, _ = self.attention(
            x, x, x,
            key_padding_mask=safe_key_padding_mask
        )

        mask = (~key_padding_mask).unsqueeze(-1).float()   # [B, 4, 1]
        summed = (attn_output * mask).sum(dim=1)
        count = mask.sum(dim=1).clamp(min=1.0)

        pooled = summed / count

        # explicitly zero out rows where all flags were missing
        pooled = pooled.clone()
        pooled[all_masked] = 0.0

        entity_vec = self.ffn(pooled)

        return entity_vec

In [ ]:
text_input_dim = 768 # BERT embedding dimension
entity_input_dim = 100 # Entity embedding dimension (e.g., from KG)
# num_subclusters is already available from previous execution: num_subclusters = 95

##2.3 Fusion Layer

The `NewsEncoder` constructs the final 128‑dimensional news representation by combining the outputs of the text and entity encoders. It first obtains a semantic vector from the `TextNewsEncoder` and an entity‑level vector from the `EntityEncoder`, then concatenates these two 128‑dimensional representations into a 256‑dimensional vector. A fusion layer projects this fused vector back into a unified 128‑dimensional space, producing the final news representation used by downstream components of the model.

In [ ]:
class NewsEncoder(nn.Module):
    def __init__(
        self,
        text_input_dim=768,  # BERT embeddings are 768-dim
        kg_input_dim=100,
        ner_input_dim=384,
        num_subclusters=96, # Determined from news_features
        model_dim=128,
        num_heads=2,
        dropout=0.3
    ):
        super().__init__()

        self.text_encoder = TextNewsEncoder(
            input_dim=text_input_dim,
            num_subclusters=num_subclusters,
            model_dim=model_dim,
            num_heads=num_heads,
            dropout=dropout
        )

        self.entity_encoder = EntityEncoder(
            kg_input_dim=kg_title_tensor.shape[1],     # 100
            ner_input_dim=ner_title_tensor.shape[1],   # 384
            model_dim=model_dim,
            num_heads=num_heads,
            dropout=dropout
        )

        # Fusion layer to combine text_vec and entity_vec
        self.fusion_layer = nn.Sequential(
            nn.Linear(model_dim * 2, model_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

    def forward(
        self,
        title_abs_emb,
        subcluster_ids,
        kg_title_emb,
        kg_abstract_emb,
        ner_title_emb,
        ner_abstract_emb,
        kg_title_flag,
        kg_abstract_flag,
        ner_title_flag,
        ner_abstract_flag
    ):
        # Encode text features
        text_vec = self.text_encoder(title_abs_emb, subcluster_ids)

        # Encode entity features
        entity_vec = self.entity_encoder(
            kg_title_emb,
            kg_abstract_emb,
            ner_title_emb,
            ner_abstract_emb,
            kg_title_flag,
            kg_abstract_flag,
            ner_title_flag,
            ner_abstract_flag
        )

        # Fuse the text and entity representations
        final_news_vec = self.fusion_layer(torch.cat([text_vec, entity_vec], dim=-1))

        return final_news_vec

#3. User Encoder

### 3.1 Multihead Self-Attention Block for User Representation Learning

The `SelfAttentionBlock` refines the sequence of clicked‑news embeddings by modelling dependencies across the user’s reading history. Rather than treating each news vector independently, it applies a Transformer‑style mechanism that captures interaction patterns and contextual relationships within the sequence.

It performs three key operations:
- **Multi‑head self‑attention**, which computes attention‑weighted interactions between all pairs of news vectors, allowing each item in the history to incorporate information from the others
- **Residual connections and layer normalization**, which stabilise the transformations and preserve the original signal while integrating contextual information
- **A position‑wise feed‑forward network**, which applies a non‑linear projection to each contextualised vector by expanding the hidden dimension fourfold and projecting it back to the original size

Together, these operations transform the raw sequence of clicked‑news embeddings into a context‑aware user representation, where each vector encodes both its own content and its relational structure within the user’s reading history.

In [ ]:
class SelfAttentionBlock(nn.Module):
    def __init__(self, hidden_dim=128, num_head=2, dropout=0.3):
        super().__init__()

        self.attn = nn.MultiheadAttention(
            embed_dim=hidden_dim,
            num_heads=num_head,
            dropout=dropout,
            batch_first=True
        )

        self.dropout1 = nn.Dropout(dropout)
        self.norm1 = nn.LayerNorm(hidden_dim)

        self.ffn = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * 4),
            nn.ReLU(),
            nn.Linear(hidden_dim * 4, hidden_dim),
        )
        self.dropout2 = nn.Dropout(dropout)
        self.norm2 = nn.LayerNorm(hidden_dim)

    def forward(self, x, key_padding_mask=None, return_attention_weights=False):
        if key_padding_mask is not None:
            all_padded = key_padding_mask.all(dim=1)   # [B]
            safe_mask = key_padding_mask.clone()
            safe_mask[all_padded] = False
        else:
            all_padded = None
            safe_mask = None

        attn_out, attn_weights = self.attn(
            x, x, x,
            key_padding_mask=safe_mask
        )

        x = self.norm1(x + self.dropout1(attn_out))
        ffn_out = self.ffn(x)
        x = self.norm2(x + self.dropout2(ffn_out))

        if all_padded is not None and all_padded.any():
            x = x.clone()
            x[all_padded] = 0.0

        if return_attention_weights:
            return x, attn_weights
        return x

### 3.2 Additive Attention Layer for User

After the Self‑Attention Block contextualises the clicked‑news sequence, the Additive Attention Layer aggregates these vectors into a single user representation by learning a relevance weight for each item and computing a weighted sum over the sequence.

In [ ]:
class AdditiveAttention(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()
        self.proj = nn.Linear(hidden_dim, hidden_dim)
        self.query = nn.Parameter(torch.randn(hidden_dim))

    def forward(self, x, mask=None):
        scores = torch.tanh(self.proj(x)) @ self.query  # (batch, seq_len)

        if mask is not None:
            all_padded = mask.all(dim=1)   # [B]
            safe_mask = mask.clone()
            safe_mask[all_padded] = False

            scores = scores.masked_fill(safe_mask, -1e9)
            weights = torch.softmax(scores, dim=1)

            # zero out weights for rows with no valid history
            weights = weights.masked_fill(mask, 0.0)
            weights = weights / weights.sum(dim=1, keepdim=True).clamp(min=1e-8)
        else:
            all_padded = None
            weights = torch.softmax(scores, dim=1)

        out = (weights.unsqueeze(-1) * x).sum(dim=1)

        if all_padded is not None and all_padded.any():
            out = out.clone()
            out[all_padded] = 0.0

        return out

### 3.3 `UserEncoder`

The `UserEncoder` transforms a user's clicked-news history into a single fixed-sze representation.

Each news item in the history is first encoded using `NewsEncoder`, producing a sequence of 128-dimensional embeddings.

This sequence is then refined by a Self‑Attention Block, which models dependencies and interaction patterns across the user’s reading history.

Finally, an Additive Attention Layer aggregates the contextualised sequence into a single user vector by learning relevance weights over the clicked items. For users with no valid history, the encoder falls back to a learnable default embedding to ensure stable behaviour.

In [ ]:
class UserEncoder(nn.Module):
    def __init__(self, news_encoder, hidden_dim=128, num_head=2, dropout=0.3):
        super().__init__()
        self.news_encoder = news_encoder
        self.attention_block = SelfAttentionBlock(hidden_dim, num_head, dropout)
        self.additive_attention = AdditiveAttention(hidden_dim)

        # Learnable fallback for users with no news reading history
        self.default_user_embedding = nn.Parameter(torch.zeros(hidden_dim))

    def forward(
        self,
        title_abs_emb_hist,
        subcluster_ids_hist,
        kg_title_emb_hist,
        kg_abstract_emb_hist,
        ner_title_emb_hist,
        ner_abstract_emb_hist,
        kg_title_flag_hist,
        kg_abstract_flag_hist,
        ner_title_flag_hist,
        ner_abstract_flag_hist,
        mask=None,
        return_attention_weights=False
    ):

        batch_size, seq_len, _ = title_abs_emb_hist.shape # Assuming these are batched

        # Encode each news item in the history using the comprehensive NewsEncoder
        # Flatten the history dimension to pass all items to NewsEncoder at once
        news_embeddings_flat = self.news_encoder(
            title_abs_emb=title_abs_emb_hist.view(-1, title_abs_emb_hist.size(-1)),
            subcluster_ids=subcluster_ids_hist.view(-1),
            kg_title_emb=kg_title_emb_hist.view(-1, kg_title_emb_hist.size(-1)),
            kg_abstract_emb=kg_abstract_emb_hist.view(-1, kg_abstract_emb_hist.size(-1)),
            ner_title_emb=ner_title_emb_hist.view(-1, ner_title_emb_hist.size(-1)),
            ner_abstract_emb=ner_abstract_emb_hist.view(-1, ner_abstract_emb_hist.size(-1)),
            kg_title_flag=kg_title_flag_hist.view(-1),
            kg_abstract_flag=kg_abstract_flag_hist.view(-1),
            ner_title_flag=ner_title_flag_hist.view(-1),
            ner_abstract_flag=ner_abstract_flag_hist.view(-1)
        )
        news_embeddings = news_embeddings_flat.view(batch_size, seq_len, -1)

        # Self-attention
        if return_attention_weights:
            attended, attn_weights = self.attention_block(
                news_embeddings, key_padding_mask=mask, return_attention_weights=True
            )
        else:
            attended = self.attention_block(
                news_embeddings, key_padding_mask=mask
            )

        # Additive attention pooling
        user_representation = self.additive_attention(attended, mask)

        # Handle users with no history (all padded) on a per-user basis
        if mask is not None:
            all_padded = mask.all(dim=1) # Identify users whose entire history is padded
            if all_padded.any():
                # Replace their representation with the default user embedding
                user_representation = user_representation.clone()
                user_representation[all_padded] = self.default_user_embedding.expand(all_padded.sum(), -1)

        if return_attention_weights:
            return user_representation, attn_weights
        return user_representation

# 4. MLP Input Preparation

Alongside news and user representations, there are several additional feature groups that will be passed into the MLP for our final predictions

These include:
- Additional User Features
- Additonal News Features
- Context Features

##4.1 Additional User Features

The Additional User Features aim to provide more in depth behavioural and preference-level signals that complement the learned user representation.

They include:
*   **Total Historical Clicks (Normalised)** : Normalised Log-Transformed Length of a user’s history
*   **Recent Favourite Category**: Most frequent news category extracted from the user's 10 most recent historical articles.
*   **Top Category 1**:  Top 1 favourite categories for each user from their historical clicks

*   **Top Category 2**: Top 2 favourite categories for each user from their historical clicks
*   **Top Category 3**: Top 3 favourite categories for each user from their historical clicks
*   **Diversity Cluster**: Label to distinguish distinct behaviour types (Cold Start, Low Diversity, Medium Diversity and High Diversity)
*   **Category Cluster** : Places users into clusters based on their top 3 categories.

In [ ]:
# Standardise column names: train uses 'pos_id', val/test use 'pos_ids'
# Make everything use 'pos_id' (scalar) and 'neg_ids' (list of 4)
if 'pos_ids' in train_user_features.columns:
    train_user_features['pos_id'] = train_user_features['pos_ids'].apply(
        lambda x: x[0] if isinstance(x, (list, np.ndarray)) else x
    )
if 'pos_ids' in val_user_features.columns:
    val_user_features['pos_id'] = val_user_features['pos_ids'].apply(
        lambda x: x[0] if isinstance(x, (list, np.ndarray)) else x
    )
if 'pos_ids' in test_user_features.columns:
    test_user_features['pos_id'] = test_user_features['pos_ids'].apply(
        lambda x: x[0] if isinstance(x, (list, np.ndarray)) else x
    )

In [ ]:
numerical_user_features = [
    'history_length',
    'diversity_ratio',
    'concentration_ratio'
]

categorical_user_features = [
    'recent_fav_cat',
    'top_cat_1',
    'top_cat_2',
    'top_cat_3',
    'diversity_cluster', # Moved here
    'interest_cluster'   # Moved here
]

# Filter features that actually exist in the DataFrame
selected_numerical_user_features = [f for f in numerical_user_features if f in train_user_features.columns]
selected_categorical_user_features = [f for f in categorical_user_features if f in train_user_features.columns]

print(f"Numerical user features: {selected_numerical_user_features}")
print(f"Categorical user features: {selected_categorical_user_features}")

Numerical user features: ['history_length', 'diversity_ratio', 'concentration_ratio']
Categorical user features: ['recent_fav_cat', 'top_cat_1', 'top_cat_2', 'top_cat_3', 'diversity_cluster', 'interest_cluster']

###4.1.1 Preprocessing User Features

In [ ]:
def preprocess_user_features(df, numerical_cols, categorical_cols, categorical_mappers=None, scaler=None):

    # 1. Extract numerical features
    user_numerical_data = df[numerical_cols].values.astype(np.float32)

    # 2. Log Transform history_length to fix the heavy-tail skew
    if 'history_length' in numerical_cols:
        hl_idx = numerical_cols.index('history_length')
        user_numerical_data[:, hl_idx] = np.log1p(user_numerical_data[:, hl_idx])

    # 3. Apply Standard Scaler
    if scaler is None:
        scaler = StandardScaler()
        user_numerical_data = scaler.fit_transform(user_numerical_data).astype(np.float32)
    else:
        user_numerical_data = scaler.transform(user_numerical_data).astype(np.float32)

    # 4. Categorical Encoding
    user_categorical_encoded_df = pd.DataFrame(index=df.index)
    current_categorical_mappers = {}
    vocab_sizes = {}

    if categorical_mappers is None: # Learn mappers from training data
        for col in categorical_cols:
            codes, uniques = pd.factorize(df[col].astype(str))
            user_categorical_encoded_df[col] = codes
            current_categorical_mappers[col] = {category: i for i, category in enumerate(uniques)}
            vocab_sizes[col] = len(uniques)
        final_mappers_to_return = current_categorical_mappers
    else: # Apply existing mappers to validation/test data
        final_mappers_to_return = categorical_mappers
        for col in categorical_cols:
            mapper = categorical_mappers[col]
            mapped_codes = df[col].astype(str).map(mapper).fillna(len(mapper)).astype(int)
            user_categorical_encoded_df[col] = mapped_codes
            vocab_sizes[col] = len(mapper) + 1

    # Return the scaler as the 5th variable
    return user_numerical_data, user_categorical_encoded_df, final_mappers_to_return, vocab_sizes, scaler

**Apply preprocessing to training data**

In [ ]:
# Process training data and capture the categorical mappers, vocab sizes, AND scaler
train_user_numerical_input, train_user_categorical_input, user_category_mappers, user_vocab_sizes, trained_scaler = preprocess_user_features(
    train_user_features,
    selected_numerical_user_features,
    selected_categorical_user_features
)

user_numerical_dense_dim = train_user_numerical_input.shape[1]

print(f"Shape of train_user_numerical_input: {train_user_numerical_input.shape}")
print(f"Shape of train_user_categorical_input: {train_user_categorical_input.shape}")
print(f"User numerical dense dimension: {user_numerical_dense_dim}")
print(f"Learned categorical mappers (first 5 for each category):")
for col, mapper in user_category_mappers.items():
    print(f"  {col}: {list(mapper.items())[:5]} ... (total {len(mapper)})")
print(f"Learned vocabulary sizes: {user_vocab_sizes}")

Shape of train_user_numerical_input: (141558, 3)
Shape of train_user_categorical_input: (141558, 6)
User numerical dense dimension: 3
Learned categorical mappers (first 5 for each category):
  recent_fav_cat: [('tvnews', 0), ('travelnews', 1), ('tv-celebrity', 2), ('autos_general', 3), ('newsgoodnews', 4)] ... (total 96)
  top_cat_1: [('tvnews', 0), ('ViolentCrime', 1), ('tv-celebrity', 2), ('autos_general', 3), ('US_ColdCases_PoliceMisconduct', 4)] ... (total 96)
  top_cat_2: [('2020Election_LegislativeReform', 0), ('PolicePursuits_DrugCrime', 1), ('markets', 2), ('travelnews', 3), ('CounterTerrorism_MiddleEastConflict', 4)] ... (total 96)
  top_cat_3: [('MLB_Awards_Rankings', 0), ('US_ColdCases_PoliceMisconduct', 1), ('basketball_nba', 2), ('ClimateInfrastructure_Pollution', 3), ('newsgoodnews', 4)] ... (total 96)
  diversity_cluster: [('0', 0), ('1', 1), ('2', 2), ('-1', 3)] ... (total 4)
  interest_cluster: [('0', 0), ('2', 1), ('1', 2), ('3', 3)] ... (total 4)
Learned vocabulary sizes: {'recent_fav_cat': 96, 'top_cat_1': 96, 'top_cat_2': 96, 'top_cat_3': 96, 'diversity_cluster': 4, 'interest_cluster': 4}

**Apply preprocessing to validation and test data**

In [ ]:
# Pass the trained_scaler in to properly normalize validation and test data
val_user_numerical_input, val_user_categorical_input, _, _, _ = preprocess_user_features(
    val_user_features,
    selected_numerical_user_features,
    selected_categorical_user_features,
    categorical_mappers=user_category_mappers,
    scaler=trained_scaler # Added scaler
)

test_user_numerical_input, test_user_categorical_input, _, _, _ = preprocess_user_features(
    test_user_features,
    selected_numerical_user_features,
    selected_categorical_user_features,
    categorical_mappers=user_category_mappers,
    scaler=trained_scaler # Added scaler
)

print(f"Shape of val_user_numerical_input: {val_user_numerical_input.shape}")
print(f"Shape of val_user_categorical_input: {val_user_categorical_input.shape}")
print(f"Shape of test_user_numerical_input: {test_user_numerical_input.shape}")
print(f"Shape of test_user_categorical_input: {test_user_categorical_input.shape}")

Shape of val_user_numerical_input: (31624, 3)
Shape of val_user_categorical_input: (31624, 6)
Shape of test_user_numerical_input: (30270, 3)
Shape of test_user_categorical_input: (30270, 6)

In [ ]:
# Convert user numerical features to tensors
train_user_numerical_tensor = torch.from_numpy(train_user_numerical_input)
val_user_numerical_tensor = torch.from_numpy(val_user_numerical_input)
test_user_numerical_tensor = torch.from_numpy(test_user_numerical_input)

# Convert user categorical features (DataFrame of integer codes) to tensors
train_user_categorical_tensors = {col: torch.from_numpy(train_user_categorical_input[col].values) for col in selected_categorical_user_features}
val_user_categorical_tensors = {col: torch.from_numpy(val_user_categorical_input[col].values) for col in selected_categorical_user_features}
test_user_categorical_tensors = {col: torch.from_numpy(test_user_categorical_input[col].values) for col in selected_categorical_user_features}

print(f"Train user numerical tensor shape: {train_user_numerical_tensor.shape}")
print(f"Train user categorical tensors (example): {train_user_categorical_tensors[selected_categorical_user_features[0]].shape}")

Train user numerical tensor shape: torch.Size([141558, 3])
Train user categorical tensors (example): torch.Size([141558])

##4.2 Additional News Features

*   **Latent Topics:** Using SVD-reduced TF-IDF vectors, we derived the top 50 most important latent topics. This feature shows the score for each article for each topic. They aim to help the model understand what is the article about beyond the leaned news embedding, enhancing its ability to match articles to users.

In [ ]:
latent_topics = news_features.filter(regex='topic_').to_numpy(dtype=np.float32)
topics_tensor = torch.from_numpy(latent_topics)
# Global lookup: news_id → integer index into the news feature tensors
news_id_to_idx_map = {nid: idx for idx, nid in enumerate(news_features['news_id'])}

##4.3 Context Features

*  **Hour of the Day (Sine)**: Cyclical encoding of the hour at which the impression occurred, using sine transformations to avoid discontinuities at midnight.

*  **Hour of the Day (Cosine)**:
Cyclical encoding of the hour at which the impression occurred, using cosine transformations to avoid discontinuities at midnight.


*  **Recency of News Article**: A freshness signal that gives higher values to newer articles and lower values to older ones. It is computed as a list of scores aligned to the candidate articles, where each score is calculated as 1 / (1 + time since the user’s first impression).

*  **Habit Score**: Captures whether the user is returning at their habitual time of day. It is computed as the cosine transformation of the hour interval between the current impression and the user’s previous impression, allowing the model to recognise consistent daily reading patterns.

In [ ]:
train_context_scalar = torch.tensor(
    train_context_features[['hour_sin', 'hour_cos', 'habit_score']].values.astype(np.float32)
)  # [N_train, 3]

val_context_scalar = torch.tensor(
    val_context_features[['hour_sin', 'hour_cos', 'habit_score']].values.astype(np.float32)
)  # [N_val, 3]

test_context_scalar = torch.tensor(
    test_context_features[['hour_sin', 'hour_cos', 'habit_score']].values.astype(np.float32)
)  # [N_test, 3]

# ── Recency score: train has fixed 5 candidates, stack into tensor ────────────
train_recency_score = torch.tensor(
    np.stack(train_context_features['recency_scores'].values),
    dtype=torch.float32
)  # [N_train, 5]

# ── Recency score: val/test have variable candidates, use lookup ──────────────
def build_recency_lookup(context_df):
    """Returns {(impression_id, news_id): recency_scores}"""
    lookup = {}
    for _, row in context_df.iterrows():
        imp_id     = row['impression_id']
        candidates = row['candidate_articles'] # Corrected column name
        scores     = row['recency_scores']
        for news_id, score in zip(candidates, scores):
            lookup[(imp_id, news_id)] = score
    return lookup

val_recency_lookup  = build_recency_lookup(val_context_features)
test_recency_lookup = build_recency_lookup(test_context_features)

print(f"train_context_scalar shape:  {train_context_scalar.shape}")
print(f"train_recency_score shape:   {train_recency_score.shape}")
print(f"val recency lookup size:     {len(val_recency_lookup)}")

train_context_scalar shape:  torch.Size([141558, 3])
train_recency_score shape:   torch.Size([141558, 5])
val recency lookup size:     1215336

# 5. MLP Implementation

The MLP implementation is similar to that of previous iterations

In [ ]:
class NewsMLP(nn.Module):
    """
    Scores a single (user, news) candidate pair -> scalar relevance score.
    """
    def __init__(
        self,
        user_numerical_dense_dim,
        user_categorical_vocab_sizes,
        topic_dim=50,
        context_dim=4,   # [hour_sin, hour_cos, habit_score, recency]
        user_repr_dim=128,
        news_repr_dim=128,
        hidden_dims=[128, 64, 32],
        embed_dim=128,
    ):
        super().__init__()

        self.user_repr_proj = nn.Linear(user_repr_dim, embed_dim)
        self.news_repr_proj = nn.Linear(news_repr_dim, embed_dim)

        self.user_numerical_dense_proj = nn.Linear(user_numerical_dense_dim, embed_dim)

        self.user_categorical_embeddings = nn.ModuleDict({
            col: nn.Embedding(vocab_size + 1, embed_dim)
            for col, vocab_size in user_categorical_vocab_sizes.items()
        })

        self.topic_proj = nn.Linear(topic_dim, embed_dim)

        self.context_proj = nn.Linear(context_dim, embed_dim)

        num_user_cat = len(user_categorical_vocab_sizes)

        total_input_dim = embed_dim * (
            1 +  # user_repr
            1 +  # news_repr
            1 +  # user_numerical
            num_user_cat +
            1 +  # topic
            1    # context_features
        )

        self.fc1 = nn.Linear(total_input_dim, hidden_dims[0])
        self.fc2 = nn.Linear(hidden_dims[0], hidden_dims[1])
        self.fc3 = nn.Linear(hidden_dims[1], hidden_dims[2])
        self.output = nn.Linear(hidden_dims[2], 1)

        self.relu = nn.ReLU()

    def forward(
        self,
        user_repr,
        news_repr,
        user_numerical_dense,
        user_categorical_input,
        topic_embed,
        context_features,   # [B, 4]
    ):
        user_repr_vec = self.relu(self.user_repr_proj(user_repr))
        news_repr_vec = self.relu(self.news_repr_proj(news_repr))

        user_numerical_vec = self.relu(self.user_numerical_dense_proj(user_numerical_dense))

        user_categorical_vecs = [
            self.user_categorical_embeddings[col](user_categorical_input[col].long())
            for col in self.user_categorical_embeddings.keys()
        ]

        topic_vec = self.relu(self.topic_proj(topic_embed))

        context_vec = self.relu(self.context_proj(context_features))

        x = torch.cat([
            user_repr_vec,
            news_repr_vec,
            user_numerical_vec,
            *user_categorical_vecs,
            topic_vec,
            context_vec,
        ], dim=1)

        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))

        score = self.output(x)
        return score.squeeze(1)

#6. Preparing Data

## 6.1 Initialise Classes to Prepare Datasets

There are 2 classes we've created to prepare our training, validation and testing datasets.

1. `HybridNewsDataset` class is used to prepare our training sets, constructing one training sample per impression by assembling all the inputs required by the model. For each impression, it gathers the users' numerical and categorical features, builds 5 candicate news items **(1 positive + 4 negatives news items)** with their raw encoder inputs. The candidate articles are then randomly shuffled to ensure that the positive item does not always appear in a fixed position, and the corresponding label is updated accordingly. It also prepares user's click history and attaches the other additional features such as latent topics and context signals (hour, habit score, recenecy). Finally, it packages all the components in a structured dictionary that can be directly consumed by the mdeol during training.

2. `HybridNewsDatasetVariable` class prepares the validation and testing samples, where each impression has a **variable number of candidate news articles**. For every impression, it retrieves the user’s numerical and categorical features, extracts raw encoder inputs for all candidate articles, and prepares the user’s padded click history. It also attaches additional candidate‑level features such as latent topic vectors, context signals (hour, habit score), and recency scores computed per (impression, news) pair. Finally, it returns all components in a structured dictionary, along with the ground‑truth labels for each candidate, enabling the model to evaluate ranking performance under realistic, variable‑sized candidate sets.

In [ ]:
class HybridNewsDataset(Dataset):
    """
    One item = one impression group.

    Returns:
      - candidate_inputs: raw encoder inputs for 5 candidates
      - history_inputs: raw encoder inputs for padded history
      - user_numerical
      - user_categorical
      - topic
      - context_features
      - label (always 0 since positive is first)
    """

    def __init__(
        self,
        user_numerical_features,         # tensor [N, user_num_dim]
        user_categorical_features_dict,  # dict {col: tensor [N]}
        pos_news_ids,                    # pd.Series [N]
        neg_news_ids,                    # pd.Series [N], each row list of 4
        history_news_ids,                # pd.Series/list [N], each row list of clicked history ids
        impression_ids,                  # pd.Series [N]
        news_id_to_idx_map,              # dict {news_id: idx}

        # Raw news encoder inputs
        all_title_abs_embeddings,        # tensor [M, text_dim]
        all_subcluster_ids,              # tensor [M]
        all_kg_title_embeddings,         # tensor [M, ent_dim]
        all_kg_abstract_embeddings,      # tensor [M, ent_dim]
        all_ner_title_embeddings,        # tensor [M, ent_dim]
        all_ner_abstract_embeddings,     # tensor [M, ent_dim]
        all_flags_matrix,                # tensor [M, 4] ordered:
                                         # [kg_title, kg_abstract, ner_title, ner_abstract]

        # Extra features for final scorer
        all_topic_embeddings,            # tensor [M, topic_dim]
        context_scalar,                  # tensor [N, 3] (hour_sin, hour_cos, habit_score)
        recency_scores,                  # tensor [N, 5]

        max_history_len=10,
        pad_news_id=None,                # optional explicit pad id
    ):
        self.user_numerical = user_numerical_features
        self.user_categorical = user_categorical_features_dict

        self.pos_news_ids = pos_news_ids.reset_index(drop=True)
        self.neg_news_ids = neg_news_ids.reset_index(drop=True)
        self.history_news_ids = history_news_ids.reset_index(drop=True)
        self.impression_ids = impression_ids.reset_index(drop=True)

        self.news_id_to_idx = news_id_to_idx_map

        # Raw encoder inputs
        self.title_abs = all_title_abs_embeddings
        self.subcluster = all_subcluster_ids
        self.kg_title = all_kg_title_embeddings
        self.kg_abs = all_kg_abstract_embeddings
        self.ner_title = all_ner_title_embeddings
        self.ner_abs = all_ner_abstract_embeddings
        self.flags = all_flags_matrix

        # Extra scorer features
        self.topic = all_topic_embeddings
        self.context_scalar = context_scalar
        self.recency_scores = recency_scores

        self.max_history_len = max_history_len

        if pad_news_id is not None:
            self.pad_news_id = pad_news_id
        else:
            # fallback: first news id in map
            self.pad_news_id = next(iter(news_id_to_idx_map.keys()))

    def __len__(self):
        return len(self.pos_news_ids)

    def _normalize_news_id(self, news_id):
        if isinstance(news_id, str):
            if news_id.startswith("N"):
                return int(news_id[1:])
            if news_id.isdigit():
                return int(news_id)
        return news_id

    def _get_news_index(self, news_id):
        news_id = self._normalize_news_id(news_id)
        idx = self.news_id_to_idx.get(news_id, None)
        if idx is None:
            raise ValueError(f"News ID {news_id} not found in news_id_to_idx_map.")
        return idx

    def _get_raw_news_features(self, news_id):
        idx = self._get_news_index(news_id)

        return {
            "title_abs_emb": self.title_abs[idx],          # [text_dim]
            "subcluster_ids": self.subcluster[idx],        # scalar
            "kg_title_emb": self.kg_title[idx],            # [ent_dim]
            "kg_abstract_emb": self.kg_abs[idx],           # [ent_dim]
            "ner_title_emb": self.ner_title[idx],          # [ent_dim]
            "ner_abstract_emb": self.ner_abs[idx],         # [ent_dim]
            "kg_title_flag": self.flags[idx][0],           # scalar
            "kg_abstract_flag": self.flags[idx][1],        # scalar
            "ner_title_flag": self.flags[idx][2],          # scalar
            "ner_abstract_flag": self.flags[idx][3],       # scalar
        }

    def _build_padded_history(self, history_ids):
        """
        Returns:
          padded_history_ids: length H
          mask: length H, True = padded, False = valid
        """
        cleaned = []
        for nid in history_ids:
            nid = self._normalize_news_id(nid)
            if nid in self.news_id_to_idx:
                cleaned.append(nid)

        cleaned = cleaned[-self.max_history_len:]

        pad_len = self.max_history_len - len(cleaned)
        padded_history_ids = [self.pad_news_id] * pad_len + cleaned
        mask = [True] * pad_len + [False] * len(cleaned)

        return padded_history_ids, mask

    def __getitem__(self, idx):
        # ---------- user ----------
        user_num = self.user_numerical[idx]  # [user_num_dim]
        user_cat = {
            col: self.user_categorical[col][idx]
            for col in self.user_categorical
        }

        # ---------- candidate ids ----------
        pos_id = self.pos_news_ids.iloc[idx]
        neg_ids = self.neg_news_ids.iloc[idx]
        candidate_ids = [pos_id] + list(neg_ids)   # [5]
        perm = np.random.permutation(len(candidate_ids))
        candidate_ids = [candidate_ids[i] for i in perm]

        # ---------- candidate raw encoder inputs ----------
        candidate_feature_dicts = [
            self._get_raw_news_features(nid)
            for nid in candidate_ids
        ]

        candidate_inputs = {
            key: torch.stack([feat[key] for feat in candidate_feature_dicts])
            for key in candidate_feature_dicts[0]
        }
        # shapes:
        # title_abs_emb      [5, text_dim]
        # subcluster_ids     [5]
        # kg_title_emb       [5, ent_dim]
        # ...
        # flags              [5]

        # ---------- history raw encoder inputs ----------
        history_ids = self.history_news_ids.iloc[idx]
        padded_history_ids, hist_mask = self._build_padded_history(history_ids)

        history_feature_dicts = [
            self._get_raw_news_features(nid)
            for nid in padded_history_ids
        ]

        history_inputs = {
            key + "_hist": torch.stack([feat[key] for feat in history_feature_dicts])
            for key in history_feature_dicts[0]
        }
        history_inputs["mask"] = torch.tensor(hist_mask, dtype=torch.bool)  # [H]

        # ---------- candidate-level extra features ----------
        candidate_indices = [self._get_news_index(nid) for nid in candidate_ids]

        topic = self.topic[candidate_indices]             # [5, topic_dim]

        recency = self.recency_scores[idx].unsqueeze(1)       # [5, 1]
        ctx_scalar = self.context_scalar[idx]                 # [3]
        ctx_scalar_expanded = ctx_scalar.unsqueeze(0).expand(len(candidate_ids), -1)  # [5, 3]
        context_features = torch.cat([ctx_scalar_expanded, recency], dim=1)           # [5, 4]

        # positive always first
        label = torch.tensor(np.where(perm == 0)[0][0], dtype=torch.long)

        return {
            "candidate_inputs": candidate_inputs,
            "history_inputs": history_inputs,
            "user_numerical": user_num,
            "user_categorical": user_cat,
            "topic": topic,
            "context_features": context_features,
            "label": label,
            "impression_id": self.impression_ids.iloc[idx],
        }

class HybridNewsDatasetVariable(Dataset):
    """
    Val/test dataset for variable number of candidates per impression.

    Returns:
      - candidate_inputs: raw encoder inputs for all candidates [C, ...]
      - history_inputs: raw encoder inputs for padded history [H, ...]
      - user_numerical
      - user_categorical
      - topic
      - context_features     [C, 4] = [hour_sin, hour_cos, habit_score, recency]
      - labels               [C]
      - impression_id
    """

    def __init__(
        self,
        user_numerical_features,         # tensor [N, user_num_dim]
        user_categorical_features_dict,  # dict {col: tensor [N]}
        interactions_df,                 # val_interactions / test_interactions
        history_news_ids,                # pd.Series/list [N], each row list of clicked history ids
        impression_ids,                  # pd.Series [N], aligned with user/context tables
        news_id_to_idx_map,

        # Raw news encoder inputs
        all_title_abs_embeddings,        # tensor [M, text_dim]
        all_subcluster_ids,              # tensor [M]
        all_kg_title_embeddings,         # tensor [M, ent_dim]
        all_kg_abstract_embeddings,      # tensor [M, ent_dim]
        all_ner_title_embeddings,        # tensor [M, ent_dim]
        all_ner_abstract_embeddings,     # tensor [M, ent_dim]
        all_flags_matrix,                # tensor [M, 4]
                                         # [kg_title, kg_abstract, ner_title, ner_abstract]

        # Extra scorer features
        all_topic_embeddings,            # tensor [M, topic_dim]
        context_scalar_tensor,           # tensor [N, 3]
        recency_lookup,                  # dict {(impression_id, news_id): score}

        max_history_len=10,
        pad_news_id=None,
    ):
        self.user_numerical = user_numerical_features
        self.user_categorical = user_categorical_features_dict
        self.interactions = interactions_df.reset_index(drop=True)
        self.history_news_ids = history_news_ids.reset_index(drop=True)
        self.impression_ids = impression_ids.reset_index(drop=True)

        self.news_id_to_idx = news_id_to_idx_map

        self.title_abs = all_title_abs_embeddings
        self.subcluster = all_subcluster_ids
        self.kg_title = all_kg_title_embeddings
        self.kg_abs = all_kg_abstract_embeddings
        self.ner_title = all_ner_title_embeddings
        self.ner_abs = all_ner_abstract_embeddings
        self.flags = all_flags_matrix

        self.topic = all_topic_embeddings

        self.context_scalar = context_scalar_tensor
        self.recency_lookup = recency_lookup

        self.max_history_len = max_history_len
        self.pad_news_id = pad_news_id if pad_news_id is not None else next(iter(news_id_to_idx_map.keys()))

    def __len__(self):
        return len(self.interactions)

    def _normalize_news_id(self, news_id):
        if isinstance(news_id, str):
            if news_id.startswith("N"):
                return int(news_id[1:])
            if news_id.isdigit():
                return int(news_id)
        return news_id

    def _get_news_index(self, news_id):
        news_id = self._normalize_news_id(news_id)
        idx = self.news_id_to_idx.get(news_id, None)
        if idx is None:
            raise ValueError(f"News ID {news_id} not found in news_id_to_idx_map.")
        return idx

    def _get_raw_news_features(self, news_id):
        idx = self._get_news_index(news_id)
        return {
            "title_abs_emb": self.title_abs[idx],
            "subcluster_ids": self.subcluster[idx],
            "kg_title_emb": self.kg_title[idx],
            "kg_abstract_emb": self.kg_abs[idx],
            "ner_title_emb": self.ner_title[idx],
            "ner_abstract_emb": self.ner_abs[idx],
            "kg_title_flag": self.flags[idx][0],
            "kg_abstract_flag": self.flags[idx][1],
            "ner_title_flag": self.flags[idx][2],
            "ner_abstract_flag": self.flags[idx][3],
        }

    def _build_padded_history(self, history_ids):
        cleaned = []
        for nid in history_ids:
            nid = self._normalize_news_id(nid)
            if nid in self.news_id_to_idx:
                cleaned.append(nid)

        cleaned = cleaned[-self.max_history_len:]
        pad_len = self.max_history_len - len(cleaned)

        padded_history_ids = [self.pad_news_id] * pad_len + cleaned
        mask = [True] * pad_len + [False] * len(cleaned)   # True = padded

        return padded_history_ids, mask

    def __getitem__(self, idx):
        row = self.interactions.iloc[idx]
        impression_id = row["impression_id"]
        candidate_ids = row["candidate_news"]   # variable length C
        labels = row["labels"]                  # variable length C

        # User features
        user_num = self.user_numerical[idx]
        user_cat = {
            col: self.user_categorical[col][idx]
            for col in self.user_categorical
        }

        # Candidate raw encoder inputs
        candidate_feature_dicts = [
            self._get_raw_news_features(nid)
            for nid in candidate_ids
        ]

        candidate_inputs = {
            key: torch.stack([feat[key] for feat in candidate_feature_dicts])
            for key in candidate_feature_dicts[0]
        }
        # candidate_inputs[key]: [C, ...]

        # History raw encoder inputs
        history_ids = self.history_news_ids.iloc[idx]
        padded_history_ids, hist_mask = self._build_padded_history(history_ids)

        history_feature_dicts = [
            self._get_raw_news_features(nid)
            for nid in padded_history_ids
        ]

        history_inputs = {
            key + "_hist": torch.stack([feat[key] for feat in history_feature_dicts])
            for key in history_feature_dicts[0]
        }
        history_inputs["mask"] = torch.tensor(hist_mask, dtype=torch.bool)  # [H]

        # Extra candidate-level features
        candidate_indices = [self._get_news_index(nid) for nid in candidate_ids]

        topic = self.topic[candidate_indices]             # [C, topic_dim]

        recency = torch.tensor(
            [self.recency_lookup.get((impression_id, nid), 0.0) for nid in candidate_ids],
            dtype=torch.float32
        ).unsqueeze(1)                                    # [C, 1]

        ctx_scalar = self.context_scalar[idx]             # [3]
        ctx_scalar_expanded = ctx_scalar.unsqueeze(0).expand(len(candidate_ids), -1)  # [C, 3]
        context_features = torch.cat([ctx_scalar_expanded, recency], dim=1)            # [C, 4]

        labels_tensor = torch.tensor(labels, dtype=torch.float32)  # [C]

        return {
            "candidate_inputs": candidate_inputs,
            "history_inputs": history_inputs,
            "user_numerical": user_num,
            "user_categorical": user_cat,
            "topic": topic,
            "context_features": context_features,
            "labels": labels_tensor,
            "impression_id": impression_id,
        }


def hybrid_collate_fn(batch):
    candidate_inputs_list = [b["candidate_inputs"] for b in batch]
    history_inputs_list = [b["history_inputs"] for b in batch]

    user_nums = [b["user_numerical"] for b in batch]
    user_cats = [b["user_categorical"] for b in batch]

    topic_list = [b["topic"] for b in batch]
    context_list = [b["context_features"] for b in batch]
    labels = [b["label"] for b in batch]
    impression_ids = [b["impression_id"] for b in batch]

    candidate_inputs_batch = {
        key: torch.stack([x[key] for x in candidate_inputs_list])
        for key in candidate_inputs_list[0]
    }
    # [B, 5, ...]

    history_inputs_batch = {
        key: torch.stack([x[key] for x in history_inputs_list])
        for key in history_inputs_list[0]
    }
    # [B, H, ...]

    user_num_batch = torch.stack(user_nums)  # [B, user_num_dim]

    user_cat_batch = {
        col: torch.stack([uc[col] for uc in user_cats])
        for col in user_cats[0]
    }  # {col: [B]}

    topic_batch = torch.stack(topic_list)              # [B, 5, topic_dim]
    context_batch = torch.stack(context_list)          # [B, 5, 4]
    label_batch = torch.stack(labels)                  # [B]

    return {
        "candidate_inputs": candidate_inputs_batch,
        "history_inputs": history_inputs_batch,
        "user_numerical": user_num_batch,
        "user_categorical": user_cat_batch,
        "topic": topic_batch,
        "context_features": context_batch,
        "label": label_batch,
        "impression_id": impression_ids,
    }

def hybrid_variable_collate_fn(batch):
    item = batch[0]

    return {
        "candidate_inputs": {
            k: v.unsqueeze(0) for k, v in item["candidate_inputs"].items()
        },  # [1, C, ...]
        "history_inputs": {
            k: v.unsqueeze(0) for k, v in item["history_inputs"].items()
        },  # [1, H, ...]
        "user_numerical": item["user_numerical"].unsqueeze(0),  # [1, user_num_dim]
        "user_categorical": {
            col: val.unsqueeze(0) for col, val in item["user_categorical"].items()
        },  # {col: [1]}
        "topic": item["topic"].unsqueeze(0),                    # [1, C, topic_dim]
        "context_features": item["context_features"].unsqueeze(0),  # [1, C, 4]
        "labels": item["labels"].unsqueeze(0),                  # [1, C]
        "impression_id": [item["impression_id"]],
    }

## 6.2 Build Train, Validation and Test Datasets

In [ ]:
# Build datasets
# NOTE: train_interactions must have 'pos_id' (scalar) and 'neg_ids' (list of 4)
#       at the impression level, matching the row order of train_user_features.

train_dataset = HybridNewsDataset(
    user_numerical_features=train_user_numerical_tensor,
    user_categorical_features_dict=train_user_categorical_tensors,
    pos_news_ids=train_user_features["pos_id"],
    neg_news_ids=train_user_features["neg_ids"],
    history_news_ids=train_user_features["history"],
    impression_ids=train_user_features["impression_id"],
    news_id_to_idx_map=news_id_to_idx_map,

    all_title_abs_embeddings=title_abs_embedding_tensor,
    all_subcluster_ids=subcluster_id_tensor,
    all_kg_title_embeddings=kg_title_tensor,
    all_kg_abstract_embeddings=kg_abstract_tensor,
    all_ner_title_embeddings=ner_title_tensor,
    all_ner_abstract_embeddings=ner_abstract_tensor,
    all_flags_matrix=flags_tensor,

    all_topic_embeddings=topics_tensor,

    context_scalar=train_context_scalar,
    recency_scores=train_recency_score,                   # now used

    max_history_len=10,
)

val_dataset = HybridNewsDatasetVariable(
    user_numerical_features=val_user_numerical_tensor,
    user_categorical_features_dict=val_user_categorical_tensors,
    interactions_df=val_interactions,
    history_news_ids=val_user_features["history"],
    impression_ids=val_user_features["impression_id"],
    news_id_to_idx_map=news_id_to_idx_map,

    all_title_abs_embeddings=title_abs_embedding_tensor,
    all_subcluster_ids=subcluster_id_tensor,
    all_kg_title_embeddings=kg_title_tensor,
    all_kg_abstract_embeddings=kg_abstract_tensor,
    all_ner_title_embeddings=ner_title_tensor,
    all_ner_abstract_embeddings=ner_abstract_tensor,
    all_flags_matrix=flags_tensor,

    all_topic_embeddings=topics_tensor,
    context_scalar_tensor=val_context_scalar,
    recency_lookup=val_recency_lookup,

    max_history_len=10,
)

test_dataset = HybridNewsDatasetVariable(
    user_numerical_features=test_user_numerical_tensor,
    user_categorical_features_dict=test_user_categorical_tensors,
    interactions_df=test_interactions,
    history_news_ids=test_user_features["history"],
    impression_ids=test_user_features["impression_id"],
    news_id_to_idx_map=news_id_to_idx_map,

    all_title_abs_embeddings=title_abs_embedding_tensor,
    all_subcluster_ids=subcluster_id_tensor,
    all_kg_title_embeddings=kg_title_tensor,
    all_kg_abstract_embeddings=kg_abstract_tensor,
    all_ner_title_embeddings=ner_title_tensor,
    all_ner_abstract_embeddings=ner_abstract_tensor,
    all_flags_matrix=flags_tensor,

    all_topic_embeddings=topics_tensor,
    context_scalar_tensor=test_context_scalar,
    recency_lookup=test_recency_lookup,

    max_history_len=10,
)

#7. Training NRMS

This section focuses on training the NRMS model performance. To understand how different architectural and regularisation choices impact performance , we train four distinct model configurations.

We vary only the number of attention heads and the dropout rate while keeping all other hyperparameters (e.g. training epochs, MLP variables, learning rate) constant.

For each configuration, we report the full set of ranking metrics (MRR, MAP, AUC, nDCG@5, nDCG@10) on both the training and test splits. This setup allows us to systematically compare how model capacity and regularisation strength influence generalisation across the four trained variants.

The table below summarises the four model configurations we have trained and the training results:

| Test No. | Model Configuration                         | MRR | MAP | AUC | nDCG@5 | nDCG@10 |
|----------|---------------------------------------------|-----|-----|-----|--------|---------|
| 1        | 4 Heads; Dropout 0.3; 10 Epochs             | 0.6638 | 0.6638 | 0.7639 | 0.7476    | 0.7476     |
| 2        | 2 Heads; Dropout 0.1; 10 Epochs             | 0.6655 | 0.6655 | 0.7653 | 0.7489    | 0.7489     |
| 3        | 2 Heads; Dropout 0.2; 10 Epochs             | 0.6580 | 0.6580 | 0.7572 | 0.7432    | 0.7432     |
| 4        | 2 Heads; Dropout 0.3; 10 Epochs             | 0.6547 | 0.6547 | 0.7534 | 0.7407    | 0.7407     |

In [ ]:
class NRMSModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.news_encoder = NewsEncoder(
            text_input_dim=title_abs_embedding_tensor.shape[1],
            kg_input_dim=kg_title_tensor.shape[1],
            ner_input_dim=ner_title_tensor.shape[1],
            num_subclusters=int(subcluster_id_tensor.max().item()) + 1,
            model_dim=128,
            num_heads=2,
            dropout=0.3,
        )
        self.user_encoder = UserEncoder(self.news_encoder)

        self.mlp = NewsMLP(
            user_repr_dim=128,
            news_repr_dim=128,
            user_numerical_dense_dim=user_numerical_dense_dim,
            user_categorical_vocab_sizes=user_vocab_sizes,
            topic_dim=topics_tensor.shape[1],
            context_dim=4,   # [hour_sin, hour_cos, habit_score, recency]
            hidden_dims=[128, 64, 32],
            embed_dim=128
        )

    def forward(
        self,
        candidate_inputs,         # dict, each [B, 5, ...]
        history_inputs,           # dict, each [B, H, ...]
        user_numerical_dense,     # [B, user_num_dim]
        user_categorical_input,   # dict {col: [B]}
        topic_embed,              # [B, 5, topic_dim]
        context_features,         # [B, 5, 4]
    ):
        batch_size = user_numerical_dense.size(0)
        num_candidates = topic_embed.size(1)   # usually 5

        # ─────────────────────────────
        # 1. Encode user from history
        # ─────────────────────────────
        user_repr = self.user_encoder(**history_inputs)   # [B, 128]

        # ─────────────────────────────
        # 2. Encode candidate news
        # flatten [B, 5, ...] -> [B*5, ...]f
        # ─────────────────────────────
        candidate_inputs_flat = {
            key: value.reshape(-1, *value.shape[2:]) if value.dim() > 2 else value.reshape(-1)
            for key, value in candidate_inputs.items()
        }

        news_repr_flat = self.news_encoder(**candidate_inputs_flat)   # [B*5, 128]
        news_repr = news_repr_flat.reshape(batch_size, num_candidates, -1)  # [B, 5, 128]

        # ─────────────────────────────
        # 3. Expand user-side features to candidate level
        # ─────────────────────────────
        user_repr_expanded = user_repr.unsqueeze(1).expand(-1, num_candidates, -1)  # [B, 5, 128]
        user_num_expanded = user_numerical_dense.unsqueeze(1).expand(-1, num_candidates, -1)  # [B, 5, d]

        user_cat_expanded = {
            col: vals.unsqueeze(1).expand(-1, num_candidates)
            for col, vals in user_categorical_input.items()
        }

        # ─────────────────────────────
        # 4. Flatten everything to pairwise [B*5, ...]
        # ─────────────────────────────
        user_repr_flat = user_repr_expanded.reshape(-1, user_repr_expanded.size(-1))
        user_num_flat = user_num_expanded.reshape(-1, user_num_expanded.size(-1))

        user_cat_flat = {
            col: vals.reshape(-1)
            for col, vals in user_cat_expanded.items()
        }

        topic_flat = topic_embed.reshape(-1, topic_embed.size(-1))
        context_flat = context_features.reshape(-1, context_features.size(-1))
        news_repr_flat = news_repr.reshape(-1, news_repr.size(-1))

        # ─────────────────────────────
        # 5. MLP scoring
        # ─────────────────────────────
        score_flat = self.mlp(
            user_repr=user_repr_flat,
            news_repr=news_repr_flat,
            user_numerical_dense=user_num_flat,
            user_categorical_input=user_cat_flat,
            topic_embed=topic_flat,
            context_features=context_flat,
        )

        scores = score_flat.reshape(batch_size, num_candidates)   # [B, 5]
        return scores

##7.1 Initialising Model

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = NRMSModel().to(device)

##7.2 Initialising Hyperparameters

In [ ]:
# Hyperparameters

learning_rate = 5e-4
batch_size    = 32
num_epochs    = 10

##7.3 Initialising DataLoaders

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    collate_fn=hybrid_collate_fn   # or listwise_collate_fn if same
)
val_loader = DataLoader(
    val_dataset,
    batch_size=1,
    shuffle=False,
    collate_fn=hybrid_variable_collate_fn
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1,
    shuffle=False,
    collate_fn=hybrid_variable_collate_fn
)

print(f"Train batches: {len(train_loader)}")
print(f"Val   batches: {len(val_loader)}")

Train batches: 4424
Val   batches: 31624

##7.4 Ranking Metrics

In [ ]:
def dcg_at_k(r, k):
    r = np.asarray(r, dtype=float)[:k]
    if r.size:
        return np.sum(r / np.log2(np.arange(2, r.size + 2)))
    return 0.0

def ndcg_at_k(r, k):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k)
    if not dcg_max:
        return 0.
    return dcg_at_k(r, k) / dcg_max

def mrr_at_k(y_true, y_score, k=None):
    predictions = sorted(zip(y_score, y_true), key=lambda x: x[0], reverse=True)
    for i, (score, label) in enumerate(predictions):
        if label == 1:
            if k is None or i < k:
                return 1.0 / (i + 1)
            return 0.0
    return 0.0

def average_precision_at_k(y_true, y_score, k=None):
    predictions = sorted(zip(y_score, y_true), key=lambda x: x[0], reverse=True)
    if k is not None:
        predictions = predictions[:k]
    num_relevant, sum_prec = 0, 0.0
    for i, (score, label) in enumerate(predictions):
        if label == 1:
            num_relevant += 1
            sum_prec     += num_relevant / (i + 1)
    return sum_prec / num_relevant if num_relevant else 0.0

def calculate_ranking_metrics(all_labels, all_scores, k_ndcg_5=5, k_ndcg_10=10):
    mrr_scores, map_scores, ndcg_5_scores, ndcg_10_scores = [], [], [], []

    for labels, scores in zip(all_labels, all_scores):
        y_true = np.array(labels)
        y_score = np.array(scores)

        if np.sum(y_true) == 0:
            continue

        mrr_scores.append(mrr_at_k(y_true, y_score))
        map_scores.append(average_precision_at_k(y_true, y_score))

        ranked = sorted(zip(y_score, y_true), key=lambda x: x[0], reverse=True)
        rel_at_rank = [label for _, label in ranked]

        ndcg_5_scores.append(ndcg_at_k(rel_at_rank, k_ndcg_5))
        ndcg_10_scores.append(ndcg_at_k(rel_at_rank, k_ndcg_10))

    return (
        np.mean(mrr_scores) if mrr_scores else 0.0,
        np.mean(map_scores) if map_scores else 0.0,
        np.mean(ndcg_5_scores) if ndcg_5_scores else 0.0,
        np.mean(ndcg_10_scores) if ndcg_10_scores else 0.0,
    )

##7.5 Training

In [ ]:
train_losses_hist = []
train_aucs_hist = []
train_mrrs_hist = []
train_maps_hist = []
train_ndcg5s_hist = []
train_ndcg10s_hist = []

val_losses_hist = []
val_aucs_hist = []
val_mrrs_hist = []
val_maps_hist = []
val_ndcg5s_hist = []
val_ndcg10s_hist = []

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    # =========================
    # TRAIN
    # =========================
    model.train()
    total_train_loss_epoch = 0.0
    total_train_samples_epoch = 0
    running_loss = 0.0

    train_all_labels = []
    train_all_scores = []

    for i, batch in enumerate(tqdm(train_loader, desc=f"Epoch {epoch+1} Training")):
        candidate_inputs = {k: v.to(device) for k, v in batch["candidate_inputs"].items()}
        history_inputs = {k: v.to(device) for k, v in batch["history_inputs"].items()}
        user_num = batch["user_numerical"].to(device)
        user_cat = {k: v.to(device) for k, v in batch["user_categorical"].items()}
        topic = batch["topic"].to(device)
        context_features = batch["context_features"].to(device)
        labels = batch["label"].to(device)   # [B], all zeros

        B = user_num.shape[0]

        optimizer.zero_grad()

        scores = model(
            candidate_inputs=candidate_inputs,
            history_inputs=history_inputs,
            user_numerical_dense=user_num,
            user_categorical_input=user_cat,
            topic_embed=topic,
            context_features=context_features,
        )

        loss = F.cross_entropy(scores, labels.long())
        loss.backward()
        optimizer.step()

        total_train_loss_epoch += loss.item() * B
        total_train_samples_epoch += B
        running_loss += loss.item()

        probs = torch.softmax(scores, dim=1)
        train_all_scores.extend(probs.detach().cpu().numpy().tolist())

        num_candidates = scores.shape[1]

        for b in range(B):
            num_candidates = scores.shape[1]
            one_hot = [0] * num_candidates
            one_hot[labels[b].item()] = 1
            train_all_labels.append(one_hot)

        if i % 100 == 99:
            tqdm.write(f"Epoch {epoch+1}, Batch {i+1}, Loss: {running_loss / 100:.4f}")
            running_loss = 0.0

    avg_train_loss = total_train_loss_epoch / total_train_samples_epoch
    train_losses_hist.append(avg_train_loss)

    flat_train_labels = [label for row in train_all_labels for label in row]
    flat_train_scores = [score for row in train_all_scores for score in row]

    if len(np.unique(flat_train_labels)) > 1:
        train_auc = roc_auc_score(flat_train_labels, flat_train_scores)
    else:
        train_auc = 0.0

    train_aucs_hist.append(train_auc)

    train_avg_mrr, train_avg_map, train_avg_ndcg_5, train_avg_ndcg_10 = calculate_ranking_metrics(
        train_all_labels,
        train_all_scores
    )

    train_mrrs_hist.append(train_avg_mrr)
    train_maps_hist.append(train_avg_map)
    train_ndcg5s_hist.append(train_avg_ndcg_5)
    train_ndcg10s_hist.append(train_avg_ndcg_10)

    print(
        f"Epoch {epoch+1} | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Train AUC: {train_auc:.4f} | "
        f"MRR: {train_avg_mrr:.4f} | "
        f"MAP: {train_avg_map:.4f} | "
        f"nDCG@5: {train_avg_ndcg_5:.4f} | "
        f"nDCG@10: {train_avg_ndcg_10:.4f}"
    )

    # =========================
    # VALIDATION
    # =========================
    model.eval()
    val_all_labels = []
    val_all_scores = []
    val_loss = 0.0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc=f"Epoch {epoch+1} Validation"):
            candidate_inputs = {k: v.to(device) for k, v in batch["candidate_inputs"].items()}
            history_inputs = {k: v.to(device) for k, v in batch["history_inputs"].items()}
            user_num = batch["user_numerical"].to(device)
            user_cat = {k: v.to(device) for k, v in batch["user_categorical"].items()}
            topic = batch["topic"].to(device)
            context_features = batch["context_features"].to(device)
            labels = batch["labels"].to(device)   # [B, C]

            scores = model(
                candidate_inputs=candidate_inputs,
                history_inputs=history_inputs,
                user_numerical_dense=user_num,
                user_categorical_input=user_cat,
                topic_embed=topic,
                context_features=context_features,
            )

            if labels.sum(dim=1).eq(1).all():
                target_idx = labels.argmax(dim=1)
                val_loss += F.cross_entropy(scores, target_idx).item()

            probs = torch.softmax(scores, dim=1)

            val_all_scores.extend(probs.cpu().numpy().tolist())
            val_all_labels.extend(labels.cpu().numpy().tolist())

    avg_val_loss = val_loss / len(val_loader)
    val_losses_hist.append(avg_val_loss)

    avg_mrr, avg_map, avg_ndcg_5, avg_ndcg_10 = calculate_ranking_metrics(
        val_all_labels,
        val_all_scores
    )

    flat_val_labels = [label for row in val_all_labels for label in row]
    flat_val_scores = [score for row in val_all_scores for score in row]

    if len(np.unique(flat_val_labels)) > 1:
        val_auc = roc_auc_score(flat_val_labels, flat_val_scores)
    else:
        val_auc = 0.0

    val_aucs_hist.append(val_auc)
    val_mrrs_hist.append(avg_mrr)
    val_maps_hist.append(avg_map)
    val_ndcg5s_hist.append(avg_ndcg_5)
    val_ndcg10s_hist.append(avg_ndcg_10)

    print(
        f"Epoch {epoch+1} | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val AUC: {val_auc:.4f} | "
        f"MRR: {avg_mrr:.4f} | "
        f"MAP: {avg_map:.4f} | "
        f"nDCG@5: {avg_ndcg_5:.4f} | "
        f"nDCG@10: {avg_ndcg_10:.4f}"
    )

print("Finished Training")

baseline_result = {
    "config": "nrms_hybrid_baseline",
    "removed": "ctr_norm_and_interaction_features",
    "val_auc": round(max(val_aucs_hist), 4),
    "val_mrr": round(max(val_mrrs_hist), 4),
    "val_map": round(max(val_maps_hist), 4),
    "val_ndcg5": round(max(val_ndcg5s_hist), 4),
    "val_ndcg10": round(max(val_ndcg10s_hist), 4),
    "best_epoch": val_ndcg5s_hist.index(max(val_ndcg5s_hist)) + 1,
}
print(f"\nBaseline stored: {baseline_result}")

Epoch 1 Training:   2%|▏         | 107/4424 [00:03<01:13, 58.61it/s]

Epoch 1, Batch 100, Loss: 1.6030

Epoch 1 Training:   5%|▍         | 211/4424 [00:05<01:09, 60.20it/s]

Epoch 1, Batch 200, Loss: 1.5504

Epoch 1 Training:   7%|▋         | 309/4424 [00:07<01:04, 63.33it/s]

Epoch 1, Batch 300, Loss: 1.5095

Epoch 1 Training:   9%|▉         | 407/4424 [00:08<01:03, 63.30it/s]

Epoch 1, Batch 400, Loss: 1.4873

Epoch 1 Training:  12%|█▏        | 512/4424 [00:10<01:02, 63.00it/s]

Epoch 1, Batch 500, Loss: 1.5088

Epoch 1 Training:  14%|█▍        | 610/4424 [00:11<01:09, 55.11it/s]

Epoch 1, Batch 600, Loss: 1.5035

Epoch 1 Training:  16%|█▌        | 708/4424 [00:13<00:58, 63.07it/s]

Epoch 1, Batch 700, Loss: 1.4806

Epoch 1 Training:  18%|█▊        | 806/4424 [00:15<00:57, 62.96it/s]

Epoch 1, Batch 800, Loss: 1.4929

Epoch 1 Training:  21%|██        | 911/4424 [00:16<00:55, 62.93it/s]

Epoch 1, Batch 900, Loss: 1.4985

Epoch 1 Training:  23%|██▎       | 1009/4424 [00:18<01:10, 48.36it/s]

Epoch 1, Batch 1000, Loss: 1.4943

Epoch 1 Training:  25%|██▌       | 1107/4424 [00:20<00:52, 63.07it/s]

Epoch 1, Batch 1100, Loss: 1.4861

Epoch 1 Training:  27%|██▋       | 1212/4424 [00:21<00:51, 62.71it/s]

Epoch 1, Batch 1200, Loss: 1.4759

Epoch 1 Training:  30%|██▉       | 1310/4424 [00:23<00:49, 63.03it/s]

Epoch 1, Batch 1300, Loss: 1.4831

Epoch 1 Training:  32%|███▏      | 1408/4424 [00:24<00:47, 63.14it/s]

Epoch 1, Batch 1400, Loss: 1.4665

Epoch 1 Training:  34%|███▍      | 1506/4424 [00:26<00:46, 63.30it/s]

Epoch 1, Batch 1500, Loss: 1.4680

Epoch 1 Training:  36%|███▋      | 1611/4424 [00:27<00:44, 63.33it/s]

Epoch 1, Batch 1600, Loss: 1.4656

Epoch 1 Training:  39%|███▊      | 1709/4424 [00:29<00:43, 62.67it/s]

Epoch 1, Batch 1700, Loss: 1.4692

Epoch 1 Training:  41%|████      | 1807/4424 [00:31<00:41, 62.98it/s]

Epoch 1, Batch 1800, Loss: 1.4848

Epoch 1 Training:  43%|████▎     | 1912/4424 [00:32<00:39, 63.25it/s]

Epoch 1, Batch 1900, Loss: 1.4549

Epoch 1 Training:  45%|████▌     | 2010/4424 [00:34<00:38, 63.08it/s]

Epoch 1, Batch 2000, Loss: 1.4260

Epoch 1 Training:  48%|████▊     | 2108/4424 [00:36<00:45, 50.50it/s]

Epoch 1, Batch 2100, Loss: 1.4685

Epoch 1 Training:  50%|████▉     | 2206/4424 [00:37<00:35, 62.94it/s]

Epoch 1, Batch 2200, Loss: 1.4530

Epoch 1 Training:  52%|█████▏    | 2311/4424 [00:39<00:33, 63.11it/s]

Epoch 1, Batch 2300, Loss: 1.4625

Epoch 1 Training:  54%|█████▍    | 2409/4424 [00:40<00:31, 63.27it/s]

Epoch 1, Batch 2400, Loss: 1.4576

Epoch 1 Training:  57%|█████▋    | 2507/4424 [00:42<00:30, 63.21it/s]

Epoch 1, Batch 2500, Loss: 1.4570

Epoch 1 Training:  59%|█████▉    | 2612/4424 [00:44<00:28, 63.26it/s]

Epoch 1, Batch 2600, Loss: 1.4611

Epoch 1 Training:  61%|██████▏   | 2710/4424 [00:45<00:26, 63.53it/s]

Epoch 1, Batch 2700, Loss: 1.4663

Epoch 1 Training:  63%|██████▎   | 2801/4424 [00:47<00:25, 63.29it/s]

Epoch 1, Batch 2800, Loss: 1.4645

Epoch 1 Training:  66%|██████▌   | 2906/4424 [00:49<00:24, 63.17it/s]

Epoch 1, Batch 2900, Loss: 1.4364

Epoch 1 Training:  68%|██████▊   | 3011/4424 [00:50<00:22, 63.41it/s]

Epoch 1, Batch 3000, Loss: 1.4481

Epoch 1 Training:  70%|███████   | 3109/4424 [00:52<00:20, 63.43it/s]

Epoch 1, Batch 3100, Loss: 1.4612

Epoch 1 Training:  72%|███████▏  | 3207/4424 [00:53<00:19, 62.74it/s]

Epoch 1, Batch 3200, Loss: 1.4499

Epoch 1 Training:  75%|███████▍  | 3312/4424 [00:55<00:17, 63.22it/s]

Epoch 1, Batch 3300, Loss: 1.4572

Epoch 1 Training:  77%|███████▋  | 3410/4424 [00:57<00:16, 62.16it/s]

Epoch 1, Batch 3400, Loss: 1.4563

Epoch 1 Training:  79%|███████▉  | 3508/4424 [00:58<00:14, 63.09it/s]

Epoch 1, Batch 3500, Loss: 1.4512

Epoch 1 Training:  82%|████████▏ | 3606/4424 [01:00<00:12, 63.09it/s]

Epoch 1, Batch 3600, Loss: 1.4464

Epoch 1 Training:  84%|████████▍ | 3711/4424 [01:01<00:11, 63.28it/s]

Epoch 1, Batch 3700, Loss: 1.4499

Epoch 1 Training:  86%|████████▌ | 3809/4424 [01:03<00:09, 63.09it/s]

Epoch 1, Batch 3800, Loss: 1.4689

Epoch 1 Training:  88%|████████▊ | 3907/4424 [01:05<00:08, 62.94it/s]

Epoch 1, Batch 3900, Loss: 1.4499

Epoch 1 Training:  91%|█████████ | 4012/4424 [01:06<00:06, 63.32it/s]

Epoch 1, Batch 4000, Loss: 1.4580

Epoch 1 Training:  93%|█████████▎| 4110/4424 [01:08<00:04, 63.62it/s]

Epoch 1, Batch 4100, Loss: 1.4385

Epoch 1 Training:  95%|█████████▌| 4208/4424 [01:10<00:03, 61.27it/s]

Epoch 1, Batch 4200, Loss: 1.4331

Epoch 1 Training:  97%|█████████▋| 4306/4424 [01:11<00:01, 63.66it/s]

Epoch 1, Batch 4300, Loss: 1.4658

Epoch 1 Training: 100%|█████████▉| 4411/4424 [01:13<00:00, 63.35it/s]

Epoch 1, Batch 4400, Loss: 1.4440

Epoch 1 Training: 100%|██████████| 4424/4424 [01:13<00:00, 60.25it/s]

Epoch 1 | Train Loss: 1.4709 | Train AUC: 0.6815 | MRR: 0.5960 | MAP: 0.5960 | nDCG@5: 0.6959 | nDCG@10: 0.6959

Epoch 1 Validation: 100%|██████████| 31624/31624 [01:37<00:00, 324.24it/s]

Epoch 1 | Val Loss: 2.0376 | Val AUC: 0.6967 | MRR: 0.2771 | MAP: 0.2568 | nDCG@5: 0.2533 | nDCG@10: 0.3147

Epoch 2 Training:   2%|▏         | 109/4424 [00:01<01:09, 62.33it/s]

Epoch 2, Batch 100, Loss: 1.4521

Epoch 2 Training:   5%|▍         | 207/4424 [00:03<01:07, 62.69it/s]

Epoch 2, Batch 200, Loss: 1.4421

Epoch 2 Training:   7%|▋         | 312/4424 [00:05<01:05, 62.63it/s]

Epoch 2, Batch 300, Loss: 1.4365

Epoch 2 Training:   9%|▉         | 410/4424 [00:06<01:04, 62.58it/s]

Epoch 2, Batch 400, Loss: 1.4373

Epoch 2 Training:  11%|█▏        | 508/4424 [00:08<01:03, 61.56it/s]

Epoch 2, Batch 500, Loss: 1.4329

Epoch 2 Training:  14%|█▎        | 606/4424 [00:10<01:01, 61.62it/s]

Epoch 2, Batch 600, Loss: 1.4379

Epoch 2 Training:  16%|█▌        | 711/4424 [00:11<00:59, 62.55it/s]

Epoch 2, Batch 700, Loss: 1.4382

Epoch 2 Training:  18%|█▊        | 809/4424 [00:13<00:57, 62.64it/s]

Epoch 2, Batch 800, Loss: 1.4488

Epoch 2 Training:  21%|██        | 907/4424 [00:14<00:56, 62.24it/s]

Epoch 2, Batch 900, Loss: 1.4407

Epoch 2 Training:  23%|██▎       | 1012/4424 [00:16<00:54, 62.36it/s]

Epoch 2, Batch 1000, Loss: 1.4384

Epoch 2 Training:  25%|██▌       | 1110/4424 [00:18<01:10, 46.94it/s]

Epoch 2, Batch 1100, Loss: 1.4388

Epoch 2 Training:  27%|██▋       | 1208/4424 [00:19<00:51, 62.26it/s]

Epoch 2, Batch 1200, Loss: 1.4263

Epoch 2 Training:  30%|██▉       | 1306/4424 [00:21<00:50, 62.29it/s]

Epoch 2, Batch 1300, Loss: 1.4469

Epoch 2 Training:  32%|███▏      | 1411/4424 [00:23<00:48, 62.37it/s]

Epoch 2, Batch 1400, Loss: 1.4424

Epoch 2 Training:  34%|███▍      | 1509/4424 [00:24<00:46, 62.45it/s]

Epoch 2, Batch 1500, Loss: 1.4231

Epoch 2 Training:  36%|███▋      | 1607/4424 [00:26<00:56, 50.04it/s]

Epoch 2, Batch 1600, Loss: 1.4323

Epoch 2 Training:  39%|███▊      | 1712/4424 [00:28<00:43, 62.30it/s]

Epoch 2, Batch 1700, Loss: 1.4304

Epoch 2 Training:  41%|████      | 1810/4424 [00:29<00:41, 62.44it/s]

Epoch 2, Batch 1800, Loss: 1.4541

Epoch 2 Training:  43%|████▎     | 1908/4424 [00:31<00:40, 62.21it/s]

Epoch 2, Batch 1900, Loss: 1.4351

Epoch 2 Training:  45%|████▌     | 2006/4424 [00:32<00:38, 62.58it/s]

Epoch 2, Batch 2000, Loss: 1.4344

Epoch 2 Training:  48%|████▊     | 2111/4424 [00:34<00:36, 62.59it/s]

Epoch 2, Batch 2100, Loss: 1.4492

Epoch 2 Training:  50%|████▉     | 2209/4424 [00:36<00:35, 62.45it/s]

Epoch 2, Batch 2200, Loss: 1.4492

Epoch 2 Training:  52%|█████▏    | 2307/4424 [00:37<00:33, 62.63it/s]

Epoch 2, Batch 2300, Loss: 1.4228

Epoch 2 Training:  55%|█████▍    | 2412/4424 [00:39<00:32, 61.07it/s]

Epoch 2, Batch 2400, Loss: 1.4455

Epoch 2 Training:  57%|█████▋    | 2510/4424 [00:41<00:30, 62.81it/s]

Epoch 2, Batch 2500, Loss: 1.4345

Epoch 2 Training:  59%|█████▉    | 2608/4424 [00:42<00:29, 61.97it/s]

Epoch 2, Batch 2600, Loss: 1.4306

Epoch 2 Training:  61%|██████    | 2706/4424 [00:44<00:27, 62.55it/s]

Epoch 2, Batch 2700, Loss: 1.4276

Epoch 2 Training:  64%|██████▎   | 2811/4424 [00:46<00:25, 62.35it/s]

Epoch 2, Batch 2800, Loss: 1.4241

Epoch 2 Training:  66%|██████▌   | 2909/4424 [00:47<00:38, 39.29it/s]

Epoch 2, Batch 2900, Loss: 1.4401

Epoch 2 Training:  68%|██████▊   | 3007/4424 [00:49<00:22, 61.99it/s]

Epoch 2, Batch 3000, Loss: 1.4427

Epoch 2 Training:  70%|███████   | 3112/4424 [00:51<00:21, 62.45it/s]

Epoch 2, Batch 3100, Loss: 1.4340

Epoch 2 Training:  73%|███████▎  | 3210/4424 [00:52<00:19, 62.43it/s]

Epoch 2, Batch 3200, Loss: 1.4291

Epoch 2 Training:  75%|███████▍  | 3308/4424 [00:54<00:17, 62.45it/s]

Epoch 2, Batch 3300, Loss: 1.4289

Epoch 2 Training:  77%|███████▋  | 3406/4424 [00:55<00:16, 62.47it/s]

Epoch 2, Batch 3400, Loss: 1.4332

Epoch 2 Training:  79%|███████▉  | 3511/4424 [00:57<00:14, 62.68it/s]

Epoch 2, Batch 3500, Loss: 1.4369

Epoch 2 Training:  82%|████████▏ | 3609/4424 [00:59<00:13, 62.47it/s]

Epoch 2, Batch 3600, Loss: 1.4169

Epoch 2 Training:  84%|████████▍ | 3707/4424 [01:00<00:11, 62.50it/s]

Epoch 2, Batch 3700, Loss: 1.4254

Epoch 2 Training:  86%|████████▌ | 3812/4424 [01:02<00:10, 59.70it/s]

Epoch 2, Batch 3800, Loss: 1.4338

Epoch 2 Training:  88%|████████▊ | 3910/4424 [01:04<00:08, 62.25it/s]

Epoch 2, Batch 3900, Loss: 1.4313

Epoch 2 Training:  91%|█████████ | 4008/4424 [01:05<00:06, 62.56it/s]

Epoch 2, Batch 4000, Loss: 1.4051

Epoch 2 Training:  93%|█████████▎| 4106/4424 [01:07<00:05, 62.51it/s]

Epoch 2, Batch 4100, Loss: 1.4254

Epoch 2 Training:  95%|█████████▌| 4211/4424 [01:09<00:03, 62.51it/s]

Epoch 2, Batch 4200, Loss: 1.4242

Epoch 2 Training:  97%|█████████▋| 4309/4424 [01:10<00:01, 62.54it/s]

Epoch 2, Batch 4300, Loss: 1.4399

Epoch 2 Training: 100%|█████████▉| 4407/4424 [01:12<00:00, 44.04it/s]

Epoch 2, Batch 4400, Loss: 1.4189

Epoch 2 Training: 100%|██████████| 4424/4424 [01:12<00:00, 60.72it/s]

Epoch 2 | Train Loss: 1.4343 | Train AUC: 0.7056 | MRR: 0.6154 | MAP: 0.6154 | nDCG@5: 0.7108 | nDCG@10: 0.7108

Epoch 2 Validation: 100%|██████████| 31624/31624 [01:37<00:00, 323.34it/s]

Epoch 2 | Val Loss: 2.0216 | Val AUC: 0.7085 | MRR: 0.2988 | MAP: 0.2763 | nDCG@5: 0.2766 | nDCG@10: 0.3358

Epoch 3 Training:   2%|▏         | 108/4424 [00:01<01:09, 62.44it/s]

Epoch 3, Batch 100, Loss: 1.4051

Epoch 3 Training:   5%|▍         | 206/4424 [00:03<01:07, 62.39it/s]

Epoch 3, Batch 200, Loss: 1.3884

Epoch 3 Training:   7%|▋         | 311/4424 [00:05<01:06, 61.49it/s]

Epoch 3, Batch 300, Loss: 1.4133

Epoch 3 Training:   9%|▉         | 409/4424 [00:06<01:04, 62.57it/s]

Epoch 3, Batch 400, Loss: 1.4180

Epoch 3 Training:  11%|█▏        | 507/4424 [00:08<01:02, 62.59it/s]

Epoch 3, Batch 500, Loss: 1.3936

Epoch 3 Training:  14%|█▍        | 612/4424 [00:10<01:01, 62.29it/s]

Epoch 3, Batch 600, Loss: 1.4106

Epoch 3 Training:  16%|█▌        | 710/4424 [00:11<01:09, 53.63it/s]

Epoch 3, Batch 700, Loss: 1.4217

Epoch 3 Training:  18%|█▊        | 808/4424 [00:13<00:58, 62.14it/s]

Epoch 3, Batch 800, Loss: 1.4018

Epoch 3 Training:  20%|██        | 906/4424 [00:15<00:56, 62.48it/s]

Epoch 3, Batch 900, Loss: 1.4076

Epoch 3 Training:  23%|██▎       | 1011/4424 [00:16<00:54, 62.64it/s]

Epoch 3, Batch 1000, Loss: 1.4082

Epoch 3 Training:  25%|██▌       | 1109/4424 [00:18<00:52, 62.60it/s]

Epoch 3, Batch 1100, Loss: 1.4173

Epoch 3 Training:  27%|██▋       | 1207/4424 [00:19<00:51, 62.55it/s]

Epoch 3, Batch 1200, Loss: 1.4206

Epoch 3 Training:  30%|██▉       | 1312/4424 [00:21<00:50, 62.09it/s]

Epoch 3, Batch 1300, Loss: 1.4174

Epoch 3 Training:  32%|███▏      | 1410/4424 [00:23<00:52, 57.47it/s]

Epoch 3, Batch 1400, Loss: 1.4097

Epoch 3 Training:  34%|███▍      | 1508/4424 [00:24<00:46, 62.23it/s]

Epoch 3, Batch 1500, Loss: 1.4144

Epoch 3 Training:  36%|███▋      | 1606/4424 [00:26<00:45, 62.37it/s]

Epoch 3, Batch 1600, Loss: 1.4017

Epoch 3 Training:  39%|███▊      | 1711/4424 [00:28<00:43, 62.42it/s]

Epoch 3, Batch 1700, Loss: 1.4100

Epoch 3 Training:  41%|████      | 1809/4424 [00:29<00:41, 62.38it/s]

Epoch 3, Batch 1800, Loss: 1.4087

Epoch 3 Training:  43%|████▎     | 1907/4424 [00:31<00:45, 55.24it/s]

Epoch 3, Batch 1900, Loss: 1.4031

Epoch 3 Training:  45%|████▌     | 2012/4424 [00:33<00:38, 62.08it/s]

Epoch 3, Batch 2000, Loss: 1.4076

Epoch 3 Training:  48%|████▊     | 2110/4424 [00:34<00:37, 62.27it/s]

Epoch 3, Batch 2100, Loss: 1.3977

Epoch 3 Training:  50%|████▉     | 2208/4424 [00:36<00:35, 62.33it/s]

Epoch 3, Batch 2200, Loss: 1.4222

Epoch 3 Training:  52%|█████▏    | 2306/4424 [00:38<00:33, 62.36it/s]

Epoch 3, Batch 2300, Loss: 1.4281

Epoch 3 Training:  54%|█████▍    | 2411/4424 [00:39<00:32, 62.28it/s]

Epoch 3, Batch 2400, Loss: 1.4025

Epoch 3 Training:  57%|█████▋    | 2509/4424 [00:41<00:30, 62.29it/s]

Epoch 3, Batch 2500, Loss: 1.4127

Epoch 3 Training:  59%|█████▉    | 2607/4424 [00:42<00:29, 61.86it/s]

Epoch 3, Batch 2600, Loss: 1.3964

Epoch 3 Training:  61%|██████▏   | 2712/4424 [00:44<00:28, 60.71it/s]

Epoch 3, Batch 2700, Loss: 1.4088

Epoch 3 Training:  64%|██████▎   | 2810/4424 [00:46<00:26, 61.89it/s]

Epoch 3, Batch 2800, Loss: 1.3795

Epoch 3 Training:  66%|██████▌   | 2908/4424 [00:48<00:24, 62.03it/s]

Epoch 3, Batch 2900, Loss: 1.3828

Epoch 3 Training:  68%|██████▊   | 3006/4424 [00:49<00:22, 62.45it/s]

Epoch 3, Batch 3000, Loss: 1.4021

Epoch 3 Training:  70%|███████   | 3111/4424 [00:51<00:20, 62.60it/s]

Epoch 3, Batch 3100, Loss: 1.3832

Epoch 3 Training:  73%|███████▎  | 3209/4424 [00:52<00:19, 62.65it/s]

Epoch 3, Batch 3200, Loss: 1.3912

Epoch 3 Training:  75%|███████▍  | 3307/4424 [00:54<00:18, 61.38it/s]

Epoch 3, Batch 3300, Loss: 1.3811

Epoch 3 Training:  77%|███████▋  | 3412/4424 [00:56<00:16, 62.06it/s]

Epoch 3, Batch 3400, Loss: 1.3972

Epoch 3 Training:  79%|███████▉  | 3510/4424 [00:57<00:14, 62.42it/s]

Epoch 3, Batch 3500, Loss: 1.3982

Epoch 3 Training:  82%|████████▏ | 3608/4424 [00:59<00:13, 62.36it/s]

Epoch 3, Batch 3600, Loss: 1.3980

Epoch 3 Training:  84%|████████▍ | 3706/4424 [01:01<00:11, 61.77it/s]

Epoch 3, Batch 3700, Loss: 1.4023

Epoch 3 Training:  86%|████████▌ | 3811/4424 [01:02<00:10, 59.76it/s]

Epoch 3, Batch 3800, Loss: 1.3999

Epoch 3 Training:  88%|████████▊ | 3907/4424 [01:04<00:08, 59.19it/s]

Epoch 3, Batch 3900, Loss: 1.3805

Epoch 3 Training:  91%|█████████ | 4009/4424 [01:06<00:06, 59.29it/s]

Epoch 3, Batch 4000, Loss: 1.3849

Epoch 3 Training:  93%|█████████▎| 4100/4424 [01:07<00:05, 59.13it/s]

Epoch 3, Batch 4100, Loss: 1.3957

Epoch 3 Training:  95%|█████████▌| 4211/4424 [01:09<00:03, 61.86it/s]

Epoch 3, Batch 4200, Loss: 1.3917

Epoch 3 Training:  97%|█████████▋| 4309/4424 [01:11<00:01, 62.20it/s]

Epoch 3, Batch 4300, Loss: 1.3876

Epoch 3 Training: 100%|█████████▉| 4407/4424 [01:12<00:00, 62.43it/s]

Epoch 3, Batch 4400, Loss: 1.3883

Epoch 3 Training: 100%|██████████| 4424/4424 [01:13<00:00, 60.38it/s]

Epoch 3 | Train Loss: 1.4021 | Train AUC: 0.7238 | MRR: 0.6303 | MAP: 0.6303 | nDCG@5: 0.7221 | nDCG@10: 0.7221

Epoch 3 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 322.59it/s]

Epoch 3 | Val Loss: 2.0019 | Val AUC: 0.7174 | MRR: 0.3162 | MAP: 0.2922 | nDCG@5: 0.2932 | nDCG@10: 0.3526

Epoch 4 Training:   2%|▏         | 108/4424 [00:01<01:12, 59.41it/s]

Epoch 4, Batch 100, Loss: 1.4039

Epoch 4 Training:   5%|▍         | 210/4424 [00:03<01:10, 59.41it/s]

Epoch 4, Batch 200, Loss: 1.3719

Epoch 4 Training:   7%|▋         | 307/4424 [00:05<01:06, 62.07it/s]

Epoch 4, Batch 300, Loss: 1.3789

Epoch 4 Training:   9%|▉         | 412/4424 [00:06<01:04, 61.94it/s]

Epoch 4, Batch 400, Loss: 1.3931

Epoch 4 Training:  12%|█▏        | 510/4424 [00:08<01:05, 59.55it/s]

Epoch 4, Batch 500, Loss: 1.3831

Epoch 4 Training:  14%|█▎        | 608/4424 [00:10<01:02, 60.59it/s]

Epoch 4, Batch 600, Loss: 1.3684

Epoch 4 Training:  16%|█▌        | 706/4424 [00:11<01:00, 60.99it/s]

Epoch 4, Batch 700, Loss: 1.3802

Epoch 4 Training:  18%|█▊        | 811/4424 [00:13<00:59, 60.97it/s]

Epoch 4, Batch 800, Loss: 1.3891

Epoch 4 Training:  21%|██        | 909/4424 [00:15<00:57, 61.20it/s]

Epoch 4, Batch 900, Loss: 1.3757

Epoch 4 Training:  23%|██▎       | 1007/4424 [00:16<00:55, 61.11it/s]

Epoch 4, Batch 1000, Loss: 1.3740

Epoch 4 Training:  25%|██▌       | 1112/4424 [00:18<00:54, 61.20it/s]

Epoch 4, Batch 1100, Loss: 1.3820

Epoch 4 Training:  27%|██▋       | 1210/4424 [00:20<00:53, 60.45it/s]

Epoch 4, Batch 1200, Loss: 1.3859

Epoch 4 Training:  30%|██▉       | 1308/4424 [00:22<00:51, 61.09it/s]

Epoch 4, Batch 1300, Loss: 1.3577

Epoch 4 Training:  32%|███▏      | 1406/4424 [00:23<00:49, 60.99it/s]

Epoch 4, Batch 1400, Loss: 1.3881

Epoch 4 Training:  34%|███▍      | 1511/4424 [00:25<00:47, 61.17it/s]

Epoch 4, Batch 1500, Loss: 1.3705

Epoch 4 Training:  36%|███▌      | 1602/4424 [00:26<00:46, 61.13it/s]

Epoch 4, Batch 1600, Loss: 1.3858

Epoch 4 Training:  39%|███▊      | 1707/4424 [00:28<00:44, 60.84it/s]

Epoch 4, Batch 1700, Loss: 1.3707

Epoch 4 Training:  41%|████      | 1812/4424 [00:30<00:42, 61.21it/s]

Epoch 4, Batch 1800, Loss: 1.3682

Epoch 4 Training:  43%|████▎     | 1910/4424 [00:32<00:41, 60.68it/s]

Epoch 4, Batch 1900, Loss: 1.3827

Epoch 4 Training:  45%|████▌     | 2008/4424 [00:33<00:39, 61.20it/s]

Epoch 4, Batch 2000, Loss: 1.3580

Epoch 4 Training:  48%|████▊     | 2106/4424 [00:35<00:38, 60.97it/s]

Epoch 4, Batch 2100, Loss: 1.3876

Epoch 4 Training:  50%|████▉     | 2211/4424 [00:37<00:36, 60.98it/s]

Epoch 4, Batch 2200, Loss: 1.3850

Epoch 4 Training:  52%|█████▏    | 2309/4424 [00:38<00:34, 60.92it/s]

Epoch 4, Batch 2300, Loss: 1.3962

Epoch 4 Training:  54%|█████▍    | 2406/4424 [00:40<00:36, 55.93it/s]

Epoch 4, Batch 2400, Loss: 1.3782

Epoch 4 Training:  57%|█████▋    | 2511/4424 [00:42<00:31, 61.14it/s]

Epoch 4, Batch 2500, Loss: 1.3906

Epoch 4 Training:  59%|█████▉    | 2609/4424 [00:43<00:29, 60.87it/s]

Epoch 4, Batch 2600, Loss: 1.3890

Epoch 4 Training:  61%|██████    | 2707/4424 [00:45<00:28, 60.78it/s]

Epoch 4, Batch 2700, Loss: 1.3842

Epoch 4 Training:  64%|██████▎   | 2812/4424 [00:47<00:26, 60.80it/s]

Epoch 4, Batch 2800, Loss: 1.3768

Epoch 4 Training:  66%|██████▌   | 2910/4424 [00:48<00:24, 60.74it/s]

Epoch 4, Batch 2900, Loss: 1.3698

Epoch 4 Training:  68%|██████▊   | 3007/4424 [00:50<00:23, 60.10it/s]

Epoch 4, Batch 3000, Loss: 1.3974

Epoch 4 Training:  70%|███████   | 3109/4424 [00:52<00:22, 59.32it/s]

Epoch 4, Batch 3100, Loss: 1.3737

Epoch 4 Training:  73%|███████▎  | 3209/4424 [00:54<00:20, 60.72it/s]

Epoch 4, Batch 3200, Loss: 1.3928

Epoch 4 Training:  75%|███████▍  | 3308/4424 [00:55<00:18, 58.91it/s]

Epoch 4, Batch 3300, Loss: 1.3655

Epoch 4 Training:  77%|███████▋  | 3410/4424 [00:57<00:17, 59.08it/s]

Epoch 4, Batch 3400, Loss: 1.3985

Epoch 4 Training:  79%|███████▉  | 3506/4424 [00:59<00:15, 59.41it/s]

Epoch 4, Batch 3500, Loss: 1.3822

Epoch 4 Training:  82%|████████▏ | 3608/4424 [01:00<00:13, 61.56it/s]

Epoch 4, Batch 3600, Loss: 1.3803

Epoch 4 Training:  84%|████████▍ | 3706/4424 [01:02<00:11, 61.93it/s]

Epoch 4, Batch 3700, Loss: 1.3939

Epoch 4 Training:  86%|████████▌ | 3811/4424 [01:04<00:11, 51.33it/s]

Epoch 4, Batch 3800, Loss: 1.3918

Epoch 4 Training:  88%|████████▊ | 3909/4424 [01:05<00:08, 62.01it/s]

Epoch 4, Batch 3900, Loss: 1.3813

Epoch 4 Training:  91%|█████████ | 4007/4424 [01:07<00:06, 62.36it/s]

Epoch 4, Batch 4000, Loss: 1.3615

Epoch 4 Training:  93%|█████████▎| 4112/4424 [01:09<00:05, 62.26it/s]

Epoch 4, Batch 4100, Loss: 1.3873

Epoch 4 Training:  95%|█████████▌| 4210/4424 [01:10<00:03, 62.22it/s]

Epoch 4, Batch 4200, Loss: 1.3730

Epoch 4 Training:  97%|█████████▋| 4308/4424 [01:12<00:01, 62.15it/s]

Epoch 4, Batch 4300, Loss: 1.3666

Epoch 4 Training: 100%|█████████▉| 4406/4424 [01:13<00:00, 62.22it/s]

Epoch 4, Batch 4400, Loss: 1.3782

Epoch 4 Training: 100%|██████████| 4424/4424 [01:14<00:00, 59.35it/s]

Epoch 4 | Train Loss: 1.3807 | Train AUC: 0.7352 | MRR: 0.6406 | MAP: 0.6406 | nDCG@5: 0.7299 | nDCG@10: 0.7299

Epoch 4 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 322.08it/s]

Epoch 4 | Val Loss: 1.9958 | Val AUC: 0.7217 | MRR: 0.3218 | MAP: 0.2965 | nDCG@5: 0.2998 | nDCG@10: 0.3591

Epoch 5 Training:   2%|▏         | 107/4424 [00:01<01:12, 59.23it/s]

Epoch 5, Batch 100, Loss: 1.3721

Epoch 5 Training:   5%|▍         | 209/4424 [00:03<01:28, 47.61it/s]

Epoch 5, Batch 200, Loss: 1.3758

Epoch 5 Training:   7%|▋         | 309/4424 [00:05<01:06, 62.15it/s]

Epoch 5, Batch 300, Loss: 1.3609

Epoch 5 Training:   9%|▉         | 407/4424 [00:07<01:04, 62.40it/s]

Epoch 5, Batch 400, Loss: 1.3808

Epoch 5 Training:  12%|█▏        | 512/4424 [00:08<01:03, 61.87it/s]

Epoch 5, Batch 500, Loss: 1.3605

Epoch 5 Training:  14%|█▍        | 610/4424 [00:10<01:01, 62.19it/s]

Epoch 5, Batch 600, Loss: 1.3966

Epoch 5 Training:  16%|█▌        | 708/4424 [00:12<01:00, 61.56it/s]

Epoch 5, Batch 700, Loss: 1.3467

Epoch 5 Training:  18%|█▊        | 806/4424 [00:13<00:57, 62.50it/s]

Epoch 5, Batch 800, Loss: 1.3902

Epoch 5 Training:  21%|██        | 911/4424 [00:15<00:56, 62.25it/s]

Epoch 5, Batch 900, Loss: 1.3703

Epoch 5 Training:  23%|██▎       | 1009/4424 [00:16<00:54, 62.44it/s]

Epoch 5, Batch 1000, Loss: 1.3560

Epoch 5 Training:  25%|██▌       | 1107/4424 [00:18<00:53, 62.13it/s]

Epoch 5, Batch 1100, Loss: 1.3570

Epoch 5 Training:  27%|██▋       | 1212/4424 [00:20<00:51, 62.34it/s]

Epoch 5, Batch 1200, Loss: 1.3843

Epoch 5 Training:  29%|██▉       | 1303/4424 [00:21<00:50, 62.13it/s]

Epoch 5, Batch 1300, Loss: 1.3774

Epoch 5 Training:  32%|███▏      | 1408/4424 [00:23<00:48, 61.96it/s]

Epoch 5, Batch 1400, Loss: 1.3767

Epoch 5 Training:  34%|███▍      | 1506/4424 [00:25<00:46, 62.44it/s]

Epoch 5, Batch 1500, Loss: 1.3887

Epoch 5 Training:  36%|███▋      | 1611/4424 [00:26<00:45, 62.47it/s]

Epoch 5, Batch 1600, Loss: 1.3478

Epoch 5 Training:  39%|███▊      | 1709/4424 [00:28<00:43, 62.31it/s]

Epoch 5, Batch 1700, Loss: 1.3700

Epoch 5 Training:  41%|████      | 1807/4424 [00:30<00:42, 62.13it/s]

Epoch 5, Batch 1800, Loss: 1.3820

Epoch 5 Training:  43%|████▎     | 1912/4424 [00:31<00:40, 61.51it/s]

Epoch 5, Batch 1900, Loss: 1.3909

Epoch 5 Training:  45%|████▌     | 2009/4424 [00:33<00:40, 59.35it/s]

Epoch 5, Batch 2000, Loss: 1.3820

Epoch 5 Training:  48%|████▊     | 2111/4424 [00:35<00:39, 59.19it/s]

Epoch 5, Batch 2100, Loss: 1.3556

Epoch 5 Training:  50%|████▉     | 2207/4424 [00:36<00:37, 59.39it/s]

Epoch 5, Batch 2200, Loss: 1.3680

Epoch 5 Training:  52%|█████▏    | 2308/4424 [00:38<00:34, 61.72it/s]

Epoch 5, Batch 2300, Loss: 1.3953

Epoch 5 Training:  54%|█████▍    | 2406/4424 [00:40<00:32, 61.71it/s]

Epoch 5, Batch 2400, Loss: 1.3952

Epoch 5 Training:  57%|█████▋    | 2511/4424 [00:41<00:31, 61.64it/s]

Epoch 5, Batch 2500, Loss: 1.3610

Epoch 5 Training:  59%|█████▉    | 2609/4424 [00:43<00:37, 48.69it/s]

Epoch 5, Batch 2600, Loss: 1.3461

Epoch 5 Training:  61%|██████    | 2706/4424 [00:45<00:29, 59.12it/s]

Epoch 5, Batch 2700, Loss: 1.3563

Epoch 5 Training:  64%|██████▎   | 2810/4424 [00:47<00:26, 62.04it/s]

Epoch 5, Batch 2800, Loss: 1.3850

Epoch 5 Training:  66%|██████▌   | 2908/4424 [00:48<00:24, 62.07it/s]

Epoch 5, Batch 2900, Loss: 1.3466

Epoch 5 Training:  68%|██████▊   | 3006/4424 [00:50<00:22, 62.00it/s]

Epoch 5, Batch 3000, Loss: 1.3567

Epoch 5 Training:  70%|███████   | 3111/4424 [00:51<00:21, 61.67it/s]

Epoch 5, Batch 3100, Loss: 1.3670

Epoch 5 Training:  73%|███████▎  | 3209/4424 [00:53<00:20, 58.48it/s]

Epoch 5, Batch 3200, Loss: 1.3569

Epoch 5 Training:  75%|███████▍  | 3307/4424 [00:55<00:17, 62.49it/s]

Epoch 5, Batch 3300, Loss: 1.3801

Epoch 5 Training:  77%|███████▋  | 3407/4424 [00:56<00:17, 58.90it/s]

Epoch 5, Batch 3400, Loss: 1.3651

Epoch 5 Training:  79%|███████▉  | 3508/4424 [00:58<00:14, 61.69it/s]

Epoch 5, Batch 3500, Loss: 1.3848

Epoch 5 Training:  82%|████████▏ | 3606/4424 [01:00<00:13, 61.72it/s]

Epoch 5, Batch 3600, Loss: 1.3655

Epoch 5 Training:  84%|████████▍ | 3711/4424 [01:01<00:11, 62.03it/s]

Epoch 5, Batch 3700, Loss: 1.3811

Epoch 5 Training:  86%|████████▌ | 3809/4424 [01:03<00:10, 61.45it/s]

Epoch 5, Batch 3800, Loss: 1.3791

Epoch 5 Training:  88%|████████▊ | 3907/4424 [01:05<00:08, 61.89it/s]

Epoch 5, Batch 3900, Loss: 1.3645

Epoch 5 Training:  91%|█████████ | 4012/4424 [01:06<00:06, 62.19it/s]

Epoch 5, Batch 4000, Loss: 1.3575

Epoch 5 Training:  93%|█████████▎| 4110/4424 [01:08<00:05, 61.14it/s]

Epoch 5, Batch 4100, Loss: 1.3808

Epoch 5 Training:  95%|█████████▌| 4208/4424 [01:10<00:03, 62.05it/s]

Epoch 5, Batch 4200, Loss: 1.3800

Epoch 5 Training:  97%|█████████▋| 4306/4424 [01:11<00:01, 62.04it/s]

Epoch 5, Batch 4300, Loss: 1.3806

Epoch 5 Training: 100%|█████████▉| 4411/4424 [01:13<00:00, 61.92it/s]

Epoch 5, Batch 4400, Loss: 1.3618

Epoch 5 Training: 100%|██████████| 4424/4424 [01:13<00:00, 59.97it/s]

Epoch 5 | Train Loss: 1.3713 | Train AUC: 0.7397 | MRR: 0.6423 | MAP: 0.6423 | nDCG@5: 0.7312 | nDCG@10: 0.7312

Epoch 5 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 320.91it/s]

Epoch 5 | Val Loss: 2.0012 | Val AUC: 0.7208 | MRR: 0.3229 | MAP: 0.2979 | nDCG@5: 0.3026 | nDCG@10: 0.3592

Epoch 6 Training:   2%|▏         | 108/4424 [00:01<01:09, 62.39it/s]

Epoch 6, Batch 100, Loss: 1.3628

Epoch 6 Training:   5%|▍         | 206/4424 [00:03<01:07, 62.45it/s]

Epoch 6, Batch 200, Loss: 1.3455

Epoch 6 Training:   7%|▋         | 311/4424 [00:05<01:05, 62.46it/s]

Epoch 6, Batch 300, Loss: 1.3509

Epoch 6 Training:   9%|▉         | 409/4424 [00:06<01:04, 61.83it/s]

Epoch 6, Batch 400, Loss: 1.4026

Epoch 6 Training:  11%|█▏        | 507/4424 [00:08<01:02, 62.48it/s]

Epoch 6, Batch 500, Loss: 1.3855

Epoch 6 Training:  14%|█▍        | 612/4424 [00:10<01:21, 46.61it/s]

Epoch 6, Batch 600, Loss: 1.3732

Epoch 6 Training:  16%|█▌        | 710/4424 [00:11<00:59, 62.26it/s]

Epoch 6, Batch 700, Loss: 1.3674

Epoch 6 Training:  18%|█▊        | 808/4424 [00:13<00:58, 62.05it/s]

Epoch 6, Batch 800, Loss: 1.3536

Epoch 6 Training:  20%|██        | 906/4424 [00:14<00:56, 62.29it/s]

Epoch 6, Batch 900, Loss: 1.3702

Epoch 6 Training:  23%|██▎       | 1011/4424 [00:16<00:54, 62.27it/s]

Epoch 6, Batch 1000, Loss: 1.3703

Epoch 6 Training:  25%|██▌       | 1109/4424 [00:18<00:56, 58.51it/s]

Epoch 6, Batch 1100, Loss: 1.3589

Epoch 6 Training:  27%|██▋       | 1207/4424 [00:19<00:51, 62.35it/s]

Epoch 6, Batch 1200, Loss: 1.3694

Epoch 6 Training:  30%|██▉       | 1312/4424 [00:21<00:49, 62.37it/s]

Epoch 6, Batch 1300, Loss: 1.3653

Epoch 6 Training:  32%|███▏      | 1410/4424 [00:23<00:48, 62.37it/s]

Epoch 6, Batch 1400, Loss: 1.3451

Epoch 6 Training:  34%|███▍      | 1508/4424 [00:24<00:46, 62.30it/s]

Epoch 6, Batch 1500, Loss: 1.3535

Epoch 6 Training:  36%|███▋      | 1606/4424 [00:26<00:45, 62.58it/s]

Epoch 6, Batch 1600, Loss: 1.3659

Epoch 6 Training:  39%|███▊      | 1711/4424 [00:27<00:43, 62.58it/s]

Epoch 6, Batch 1700, Loss: 1.3616

Epoch 6 Training:  41%|████      | 1809/4424 [00:29<00:47, 55.02it/s]

Epoch 6, Batch 1800, Loss: 1.3767

Epoch 6 Training:  43%|████▎     | 1907/4424 [00:31<00:40, 62.29it/s]

Epoch 6, Batch 1900, Loss: 1.3800

Epoch 6 Training:  45%|████▌     | 2012/4424 [00:33<00:38, 62.40it/s]

Epoch 6, Batch 2000, Loss: 1.3491

Epoch 6 Training:  48%|████▊     | 2110/4424 [00:34<00:37, 62.45it/s]

Epoch 6, Batch 2100, Loss: 1.3328

Epoch 6 Training:  50%|████▉     | 2208/4424 [00:36<00:35, 62.33it/s]

Epoch 6, Batch 2200, Loss: 1.3555

Epoch 6 Training:  52%|█████▏    | 2299/4424 [00:37<00:34, 62.50it/s]

Epoch 6, Batch 2300, Loss: 1.3506

Epoch 6 Training:  54%|█████▍    | 2411/4424 [00:39<00:32, 61.39it/s]

Epoch 6, Batch 2400, Loss: 1.3586

Epoch 6 Training:  57%|█████▋    | 2509/4424 [00:41<00:31, 61.53it/s]

Epoch 6, Batch 2500, Loss: 1.3482

Epoch 6 Training:  59%|█████▉    | 2607/4424 [00:42<00:29, 61.87it/s]

Epoch 6, Batch 2600, Loss: 1.3746

Epoch 6 Training:  61%|██████▏   | 2712/4424 [00:44<00:27, 62.13it/s]

Epoch 6, Batch 2700, Loss: 1.3484

Epoch 6 Training:  64%|██████▎   | 2810/4424 [00:46<00:25, 62.40it/s]

Epoch 6, Batch 2800, Loss: 1.3812

Epoch 6 Training:  66%|██████▌   | 2908/4424 [00:47<00:24, 62.41it/s]

Epoch 6, Batch 2900, Loss: 1.3574

Epoch 6 Training:  68%|██████▊   | 3006/4424 [00:49<00:22, 62.05it/s]

Epoch 6, Batch 3000, Loss: 1.3714

Epoch 6 Training:  70%|███████   | 3111/4424 [00:51<00:21, 61.46it/s]

Epoch 6, Batch 3100, Loss: 1.3777

Epoch 6 Training:  72%|███████▏  | 3206/4424 [00:52<00:21, 57.90it/s]

Epoch 6, Batch 3200, Loss: 1.3646

Epoch 6 Training:  75%|███████▍  | 3308/4424 [00:54<00:18, 58.83it/s]

Epoch 6, Batch 3300, Loss: 1.3585

Epoch 6 Training:  77%|███████▋  | 3410/4424 [00:56<00:17, 59.08it/s]

Epoch 6, Batch 3400, Loss: 1.3807

Epoch 6 Training:  79%|███████▉  | 3506/4424 [00:58<00:15, 59.37it/s]

Epoch 6, Batch 3500, Loss: 1.3812

Epoch 6 Training:  82%|████████▏ | 3609/4424 [00:59<00:13, 59.21it/s]

Epoch 6, Batch 3600, Loss: 1.3747

Epoch 6 Training:  84%|████████▍ | 3711/4424 [01:01<00:12, 58.73it/s]

Epoch 6, Batch 3700, Loss: 1.3527

Epoch 6 Training:  86%|████████▌ | 3807/4424 [01:03<00:10, 58.91it/s]

Epoch 6, Batch 3800, Loss: 1.3713

Epoch 6 Training:  88%|████████▊ | 3910/4424 [01:05<00:08, 62.54it/s]

Epoch 6, Batch 3900, Loss: 1.3731

Epoch 6 Training:  91%|█████████ | 4008/4424 [01:06<00:06, 62.24it/s]

Epoch 6, Batch 4000, Loss: 1.3494

Epoch 6 Training:  93%|█████████▎| 4106/4424 [01:08<00:05, 62.36it/s]

Epoch 6, Batch 4100, Loss: 1.3555

Epoch 6 Training:  95%|█████████▌| 4211/4424 [01:09<00:03, 62.29it/s]

Epoch 6, Batch 4200, Loss: 1.3881

Epoch 6 Training:  97%|█████████▋| 4309/4424 [01:11<00:01, 62.30it/s]

Epoch 6, Batch 4300, Loss: 1.3838

Epoch 6 Training: 100%|█████████▉| 4407/4424 [01:13<00:00, 61.99it/s]

Epoch 6, Batch 4400, Loss: 1.3621

Epoch 6 Training: 100%|██████████| 4424/4424 [01:13<00:00, 60.30it/s]

Epoch 6 | Train Loss: 1.3653 | Train AUC: 0.7425 | MRR: 0.6456 | MAP: 0.6456 | nDCG@5: 0.7338 | nDCG@10: 0.7338

Epoch 6 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 320.60it/s]

Epoch 6 | Val Loss: 1.9876 | Val AUC: 0.7240 | MRR: 0.3249 | MAP: 0.2996 | nDCG@5: 0.3025 | nDCG@10: 0.3620

Epoch 7 Training:   3%|▎         | 111/4424 [00:01<01:12, 59.25it/s]

Epoch 7, Batch 100, Loss: 1.3470

Epoch 7 Training:   5%|▍         | 212/4424 [00:03<01:08, 61.58it/s]

Epoch 7, Batch 200, Loss: 1.3509

Epoch 7 Training:   7%|▋         | 310/4424 [00:05<01:06, 62.15it/s]

Epoch 7, Batch 300, Loss: 1.3379

Epoch 7 Training:   9%|▉         | 408/4424 [00:07<01:05, 60.96it/s]

Epoch 7, Batch 400, Loss: 1.3445

Epoch 7 Training:  11%|█▏        | 506/4424 [00:08<01:03, 61.96it/s]

Epoch 7, Batch 500, Loss: 1.3265

Epoch 7 Training:  14%|█▍        | 611/4424 [00:10<01:01, 62.27it/s]

Epoch 7, Batch 600, Loss: 1.3437

Epoch 7 Training:  16%|█▌        | 709/4424 [00:11<00:59, 62.05it/s]

Epoch 7, Batch 700, Loss: 1.3683

Epoch 7 Training:  18%|█▊        | 807/4424 [00:13<01:16, 47.08it/s]

Epoch 7, Batch 800, Loss: 1.3909

Epoch 7 Training:  21%|██        | 912/4424 [00:15<00:56, 62.19it/s]

Epoch 7, Batch 900, Loss: 1.3862

Epoch 7 Training:  23%|██▎       | 1010/4424 [00:16<00:55, 61.92it/s]

Epoch 7, Batch 1000, Loss: 1.3296

Epoch 7 Training:  25%|██▌       | 1108/4424 [00:18<00:53, 62.12it/s]

Epoch 7, Batch 1100, Loss: 1.3494

Epoch 7 Training:  27%|██▋       | 1206/4424 [00:20<00:51, 62.25it/s]

Epoch 7, Batch 1200, Loss: 1.3596

Epoch 7 Training:  30%|██▉       | 1311/4424 [00:21<00:49, 62.30it/s]

Epoch 7, Batch 1300, Loss: 1.3535

Epoch 7 Training:  32%|███▏      | 1409/4424 [00:23<00:48, 62.43it/s]

Epoch 7, Batch 1400, Loss: 1.3476

Epoch 7 Training:  34%|███▍      | 1507/4424 [00:25<00:55, 52.93it/s]

Epoch 7, Batch 1500, Loss: 1.3601

Epoch 7 Training:  36%|███▋      | 1612/4424 [00:26<00:45, 62.20it/s]

Epoch 7, Batch 1600, Loss: 1.3549

Epoch 7 Training:  39%|███▊      | 1710/4424 [00:28<00:43, 61.74it/s]

Epoch 7, Batch 1700, Loss: 1.3576

Epoch 7 Training:  41%|████      | 1808/4424 [00:30<00:42, 62.09it/s]

Epoch 7, Batch 1800, Loss: 1.3634

Epoch 7 Training:  43%|████▎     | 1906/4424 [00:31<00:40, 62.19it/s]

Epoch 7, Batch 1900, Loss: 1.3562

Epoch 7 Training:  45%|████▌     | 2011/4424 [00:33<00:48, 49.41it/s]

Epoch 7, Batch 2000, Loss: 1.3407

Epoch 7 Training:  48%|████▊     | 2109/4424 [00:35<00:37, 62.29it/s]

Epoch 7, Batch 2100, Loss: 1.3698

Epoch 7 Training:  50%|████▉     | 2207/4424 [00:36<00:35, 62.41it/s]

Epoch 7, Batch 2200, Loss: 1.3703

Epoch 7 Training:  52%|█████▏    | 2312/4424 [00:38<00:33, 62.24it/s]

Epoch 7, Batch 2300, Loss: 1.3524

Epoch 7 Training:  54%|█████▍    | 2410/4424 [00:39<00:32, 62.09it/s]

Epoch 7, Batch 2400, Loss: 1.3511

Epoch 7 Training:  57%|█████▋    | 2508/4424 [00:41<00:30, 62.45it/s]

Epoch 7, Batch 2500, Loss: 1.3667

Epoch 7 Training:  59%|█████▉    | 2606/4424 [00:43<00:29, 62.60it/s]

Epoch 7, Batch 2600, Loss: 1.3515

Epoch 7 Training:  61%|██████▏   | 2711/4424 [00:44<00:27, 62.74it/s]

Epoch 7, Batch 2700, Loss: 1.3489

Epoch 7 Training:  63%|██████▎   | 2809/4424 [00:46<00:30, 52.79it/s]

Epoch 7, Batch 2800, Loss: 1.3577

Epoch 7 Training:  66%|██████▌   | 2907/4424 [00:48<00:24, 61.89it/s]

Epoch 7, Batch 2900, Loss: 1.3587

Epoch 7 Training:  68%|██████▊   | 3012/4424 [00:49<00:22, 62.39it/s]

Epoch 7, Batch 3000, Loss: 1.3551

Epoch 7 Training:  70%|███████   | 3110/4424 [00:51<00:21, 61.81it/s]

Epoch 7, Batch 3100, Loss: 1.3567

Epoch 7 Training:  73%|███████▎  | 3208/4424 [00:53<00:19, 61.66it/s]

Epoch 7, Batch 3200, Loss: 1.3684

Epoch 7 Training:  75%|███████▍  | 3306/4424 [00:54<00:18, 61.75it/s]

Epoch 7, Batch 3300, Loss: 1.3664

Epoch 7 Training:  77%|███████▋  | 3411/4424 [00:56<00:17, 58.26it/s]

Epoch 7, Batch 3400, Loss: 1.3701

Epoch 7 Training:  79%|███████▉  | 3509/4424 [00:58<00:14, 62.12it/s]

Epoch 7, Batch 3500, Loss: 1.3562

Epoch 7 Training:  82%|████████▏ | 3607/4424 [00:59<00:13, 62.15it/s]

Epoch 7, Batch 3600, Loss: 1.3747

Epoch 7 Training:  84%|████████▍ | 3712/4424 [01:01<00:11, 61.74it/s]

Epoch 7, Batch 3700, Loss: 1.3603

Epoch 7 Training:  86%|████████▌ | 3809/4424 [01:03<00:10, 59.70it/s]

Epoch 7, Batch 3800, Loss: 1.3515

Epoch 7 Training:  88%|████████▊ | 3911/4424 [01:04<00:08, 59.32it/s]

Epoch 7, Batch 3900, Loss: 1.3568

Epoch 7 Training:  91%|█████████ | 4007/4424 [01:06<00:07, 59.28it/s]

Epoch 7, Batch 4000, Loss: 1.3531

Epoch 7 Training:  93%|█████████▎| 4106/4424 [01:08<00:05, 59.32it/s]

Epoch 7, Batch 4100, Loss: 1.3621

Epoch 7 Training:  95%|█████████▌| 4210/4424 [01:09<00:03, 59.47it/s]

Epoch 7, Batch 4200, Loss: 1.3566

Epoch 7 Training:  97%|█████████▋| 4307/4424 [01:11<00:02, 56.86it/s]

Epoch 7, Batch 4300, Loss: 1.3533

Epoch 7 Training: 100%|█████████▉| 4410/4424 [01:13<00:00, 59.20it/s]

Epoch 7, Batch 4400, Loss: 1.3673

Epoch 7 Training: 100%|██████████| 4424/4424 [01:13<00:00, 59.97it/s]

Epoch 7 | Train Loss: 1.3568 | Train AUC: 0.7466 | MRR: 0.6489 | MAP: 0.6489 | nDCG@5: 0.7363 | nDCG@10: 0.7363

Epoch 7 Validation: 100%|██████████| 31624/31624 [01:37<00:00, 322.81it/s]

Epoch 7 | Val Loss: 2.0117 | Val AUC: 0.7179 | MRR: 0.3186 | MAP: 0.2943 | nDCG@5: 0.2971 | nDCG@10: 0.3556

Epoch 8 Training:   2%|▏         | 107/4424 [00:01<01:12, 59.37it/s]

Epoch 8, Batch 100, Loss: 1.3592

Epoch 8 Training:   5%|▍         | 206/4424 [00:03<01:10, 59.67it/s]

Epoch 8, Batch 200, Loss: 1.3563

Epoch 8 Training:   7%|▋         | 309/4424 [00:05<01:09, 59.44it/s]

Epoch 8, Batch 300, Loss: 1.3581

Epoch 8 Training:   9%|▉         | 407/4424 [00:06<01:07, 59.52it/s]

Epoch 8, Batch 400, Loss: 1.3503

Epoch 8 Training:  12%|█▏        | 510/4424 [00:08<01:05, 59.56it/s]

Epoch 8, Batch 500, Loss: 1.3614

Epoch 8 Training:  14%|█▎        | 607/4424 [00:10<01:04, 59.61it/s]

Epoch 8, Batch 600, Loss: 1.3580

Epoch 8 Training:  16%|█▌        | 710/4424 [00:12<01:02, 58.97it/s]

Epoch 8, Batch 700, Loss: 1.3582

Epoch 8 Training:  18%|█▊        | 807/4424 [00:13<01:00, 59.38it/s]

Epoch 8, Batch 800, Loss: 1.3353

Epoch 8 Training:  21%|██        | 909/4424 [00:15<00:58, 59.68it/s]

Epoch 8, Batch 900, Loss: 1.3520

Epoch 8 Training:  23%|██▎       | 1006/4424 [00:17<00:58, 58.09it/s]

Epoch 8, Batch 1000, Loss: 1.3486

Epoch 8 Training:  25%|██▌       | 1109/4424 [00:18<00:55, 59.20it/s]

Epoch 8, Batch 1100, Loss: 1.3452

Epoch 8 Training:  27%|██▋       | 1207/4424 [00:20<00:53, 59.61it/s]

Epoch 8, Batch 1200, Loss: 1.3349

Epoch 8 Training:  30%|██▉       | 1309/4424 [00:22<00:52, 59.28it/s]

Epoch 8, Batch 1300, Loss: 1.3417

Epoch 8 Training:  32%|███▏      | 1406/4424 [00:24<00:50, 59.35it/s]

Epoch 8, Batch 1400, Loss: 1.3448

Epoch 8 Training:  34%|███▍      | 1511/4424 [00:25<00:48, 59.46it/s]

Epoch 8, Batch 1500, Loss: 1.3460

Epoch 8 Training:  36%|███▋      | 1609/4424 [00:27<00:47, 59.04it/s]

Epoch 8, Batch 1600, Loss: 1.3593

Epoch 8 Training:  39%|███▊      | 1710/4424 [00:29<00:43, 62.38it/s]

Epoch 8, Batch 1700, Loss: 1.3575

Epoch 8 Training:  41%|████      | 1808/4424 [00:30<00:41, 62.54it/s]

Epoch 8, Batch 1800, Loss: 1.3477

Epoch 8 Training:  43%|████▎     | 1906/4424 [00:32<00:40, 61.76it/s]

Epoch 8, Batch 1900, Loss: 1.3745

Epoch 8 Training:  45%|████▌     | 2011/4424 [00:34<00:38, 62.76it/s]

Epoch 8, Batch 2000, Loss: 1.3691

Epoch 8 Training:  48%|████▊     | 2109/4424 [00:35<00:37, 62.47it/s]

Epoch 8, Batch 2100, Loss: 1.3392

Epoch 8 Training:  50%|████▉     | 2207/4424 [00:37<00:35, 62.36it/s]

Epoch 8, Batch 2200, Loss: 1.3507

Epoch 8 Training:  52%|█████▏    | 2312/4424 [00:39<00:34, 61.61it/s]

Epoch 8, Batch 2300, Loss: 1.3515

Epoch 8 Training:  54%|█████▍    | 2410/4424 [00:40<00:32, 62.41it/s]

Epoch 8, Batch 2400, Loss: 1.3449

Epoch 8 Training:  57%|█████▋    | 2508/4424 [00:42<00:30, 62.29it/s]

Epoch 8, Batch 2500, Loss: 1.3456

Epoch 8 Training:  59%|█████▉    | 2606/4424 [00:44<00:40, 45.17it/s]

Epoch 8, Batch 2600, Loss: 1.3547

Epoch 8 Training:  61%|██████▏   | 2711/4424 [00:45<00:27, 62.41it/s]

Epoch 8, Batch 2700, Loss: 1.3614

Epoch 8 Training:  63%|██████▎   | 2809/4424 [00:47<00:25, 62.28it/s]

Epoch 8, Batch 2800, Loss: 1.3586

Epoch 8 Training:  66%|██████▌   | 2907/4424 [00:48<00:24, 62.51it/s]

Epoch 8, Batch 2900, Loss: 1.3528

Epoch 8 Training:  68%|██████▊   | 3012/4424 [00:50<00:22, 62.02it/s]

Epoch 8, Batch 3000, Loss: 1.3501

Epoch 8 Training:  70%|███████   | 3109/4424 [00:52<00:22, 58.94it/s]

Epoch 8, Batch 3100, Loss: 1.3376

Epoch 8 Training:  73%|███████▎  | 3211/4424 [00:54<00:21, 56.11it/s]

Epoch 8, Batch 3200, Loss: 1.3530

Epoch 8 Training:  75%|███████▍  | 3310/4424 [00:55<00:17, 62.20it/s]

Epoch 8, Batch 3300, Loss: 1.3452

Epoch 8 Training:  77%|███████▋  | 3408/4424 [00:57<00:16, 61.69it/s]

Epoch 8, Batch 3400, Loss: 1.3561

Epoch 8 Training:  79%|███████▉  | 3506/4424 [00:59<00:14, 62.14it/s]

Epoch 8, Batch 3500, Loss: 1.3574

Epoch 8 Training:  82%|████████▏ | 3611/4424 [01:00<00:13, 61.73it/s]

Epoch 8, Batch 3600, Loss: 1.3554

Epoch 8 Training:  84%|████████▍ | 3709/4424 [01:02<00:11, 62.27it/s]

Epoch 8, Batch 3700, Loss: 1.3396

Epoch 8 Training:  86%|████████▌ | 3808/4424 [01:04<00:10, 59.22it/s]

Epoch 8, Batch 3800, Loss: 1.3526

Epoch 8 Training:  88%|████████▊ | 3912/4424 [01:05<00:08, 62.12it/s]

Epoch 8, Batch 3900, Loss: 1.3447

Epoch 8 Training:  91%|█████████ | 4009/4424 [01:07<00:06, 59.46it/s]

Epoch 8, Batch 4000, Loss: 1.3557

Epoch 8 Training:  93%|█████████▎| 4111/4424 [01:09<00:05, 58.13it/s]

Epoch 8, Batch 4100, Loss: 1.3787

Epoch 8 Training:  95%|█████████▌| 4207/4424 [01:10<00:03, 59.00it/s]

Epoch 8, Batch 4200, Loss: 1.3657

Epoch 8 Training:  97%|█████████▋| 4309/4424 [01:12<00:01, 58.60it/s]

Epoch 8, Batch 4300, Loss: 1.3554

Epoch 8 Training: 100%|█████████▉| 4411/4424 [01:14<00:00, 59.01it/s]

Epoch 8, Batch 4400, Loss: 1.3473

Epoch 8 Training: 100%|██████████| 4424/4424 [01:14<00:00, 59.24it/s]

Epoch 8 | Train Loss: 1.3526 | Train AUC: 0.7486 | MRR: 0.6503 | MAP: 0.6503 | nDCG@5: 0.7373 | nDCG@10: 0.7373

Epoch 8 Validation: 100%|██████████| 31624/31624 [01:37<00:00, 324.39it/s]

Epoch 8 | Val Loss: 1.9923 | Val AUC: 0.7246 | MRR: 0.3278 | MAP: 0.3019 | nDCG@5: 0.3075 | nDCG@10: 0.3653

Epoch 9 Training:   2%|▏         | 107/4424 [00:01<01:13, 59.04it/s]

Epoch 9, Batch 100, Loss: 1.3249

Epoch 9 Training:   5%|▍         | 209/4424 [00:03<01:11, 59.24it/s]

Epoch 9, Batch 200, Loss: 1.3331

Epoch 9 Training:   7%|▋         | 311/4424 [00:05<01:11, 57.91it/s]

Epoch 9, Batch 300, Loss: 1.3396

Epoch 9 Training:   9%|▉         | 407/4424 [00:07<01:09, 57.60it/s]

Epoch 9, Batch 400, Loss: 1.3343

Epoch 9 Training:  12%|█▏        | 510/4424 [00:08<01:06, 59.24it/s]

Epoch 9, Batch 500, Loss: 1.3262

Epoch 9 Training:  14%|█▎        | 606/4424 [00:10<01:04, 59.27it/s]

Epoch 9, Batch 600, Loss: 1.3292

Epoch 9 Training:  16%|█▌        | 709/4424 [00:12<01:02, 59.24it/s]

Epoch 9, Batch 700, Loss: 1.3349

Epoch 9 Training:  18%|█▊        | 806/4424 [00:13<00:58, 61.65it/s]

Epoch 9, Batch 800, Loss: 1.3281

Epoch 9 Training:  21%|██        | 911/4424 [00:15<00:56, 61.65it/s]

Epoch 9, Batch 900, Loss: 1.3459

Epoch 9 Training:  23%|██▎       | 1002/4424 [00:17<00:55, 61.81it/s]

Epoch 9, Batch 1000, Loss: 1.3470

Epoch 9 Training:  25%|██▌       | 1107/4424 [00:18<00:53, 61.79it/s]

Epoch 9, Batch 1100, Loss: 1.3530

Epoch 9 Training:  27%|██▋       | 1212/4424 [00:20<00:51, 61.95it/s]

Epoch 9, Batch 1200, Loss: 1.3352

Epoch 9 Training:  30%|██▉       | 1310/4424 [00:22<00:50, 61.97it/s]

Epoch 9, Batch 1300, Loss: 1.3530

Epoch 9 Training:  32%|███▏      | 1408/4424 [00:23<00:48, 62.01it/s]

Epoch 9, Batch 1400, Loss: 1.3438

Epoch 9 Training:  34%|███▍      | 1506/4424 [00:25<01:03, 45.62it/s]

Epoch 9, Batch 1500, Loss: 1.3408

Epoch 9 Training:  36%|███▋      | 1611/4424 [00:27<00:45, 61.49it/s]

Epoch 9, Batch 1600, Loss: 1.3387

Epoch 9 Training:  39%|███▊      | 1709/4424 [00:28<00:43, 61.87it/s]

Epoch 9, Batch 1700, Loss: 1.3459

Epoch 9 Training:  41%|████      | 1807/4424 [00:30<00:42, 61.71it/s]

Epoch 9, Batch 1800, Loss: 1.3431

Epoch 9 Training:  43%|████▎     | 1912/4424 [00:32<00:40, 61.77it/s]

Epoch 9, Batch 1900, Loss: 1.3489

Epoch 9 Training:  45%|████▌     | 2010/4424 [00:33<00:39, 61.37it/s]

Epoch 9, Batch 2000, Loss: 1.3466

Epoch 9 Training:  48%|████▊     | 2108/4424 [00:35<00:37, 61.61it/s]

Epoch 9, Batch 2100, Loss: 1.3608

Epoch 9 Training:  50%|████▉     | 2206/4424 [00:37<00:36, 61.42it/s]

Epoch 9, Batch 2200, Loss: 1.3619

Epoch 9 Training:  52%|█████▏    | 2311/4424 [00:39<00:34, 60.71it/s]

Epoch 9, Batch 2300, Loss: 1.3704

Epoch 9 Training:  54%|█████▍    | 2409/4424 [00:40<00:32, 61.49it/s]

Epoch 9, Batch 2400, Loss: 1.3382

Epoch 9 Training:  57%|█████▋    | 2507/4424 [00:42<00:30, 61.90it/s]

Epoch 9, Batch 2500, Loss: 1.3543

Epoch 9 Training:  59%|█████▉    | 2612/4424 [00:43<00:29, 61.56it/s]

Epoch 9, Batch 2600, Loss: 1.3375

Epoch 9 Training:  61%|██████▏   | 2710/4424 [00:45<00:28, 60.08it/s]

Epoch 9, Batch 2700, Loss: 1.3246

Epoch 9 Training:  63%|██████▎   | 2807/4424 [00:47<00:35, 45.21it/s]

Epoch 9, Batch 2800, Loss: 1.3258

Epoch 9 Training:  66%|██████▌   | 2909/4424 [00:49<00:26, 58.15it/s]

Epoch 9, Batch 2900, Loss: 1.3526

Epoch 9 Training:  68%|██████▊   | 3011/4424 [00:50<00:23, 59.06it/s]

Epoch 9, Batch 3000, Loss: 1.3541

Epoch 9 Training:  70%|███████   | 3107/4424 [00:52<00:22, 58.64it/s]

Epoch 9, Batch 3100, Loss: 1.3295

Epoch 9 Training:  73%|███████▎  | 3209/4424 [00:54<00:20, 59.12it/s]

Epoch 9, Batch 3200, Loss: 1.3429

Epoch 9 Training:  75%|███████▍  | 3308/4424 [00:55<00:18, 61.73it/s]

Epoch 9, Batch 3300, Loss: 1.3480

Epoch 9 Training:  77%|███████▋  | 3406/4424 [00:57<00:16, 62.22it/s]

Epoch 9, Batch 3400, Loss: 1.3571

Epoch 9 Training:  79%|███████▉  | 3511/4424 [00:59<00:14, 62.06it/s]

Epoch 9, Batch 3500, Loss: 1.3468

Epoch 9 Training:  82%|████████▏ | 3609/4424 [01:00<00:13, 61.93it/s]

Epoch 9, Batch 3600, Loss: 1.3237

Epoch 9 Training:  84%|████████▍ | 3707/4424 [01:02<00:11, 60.95it/s]

Epoch 9, Batch 3700, Loss: 1.3539

Epoch 9 Training:  86%|████████▌ | 3812/4424 [01:04<00:09, 62.43it/s]

Epoch 9, Batch 3800, Loss: 1.3517

Epoch 9 Training:  88%|████████▊ | 3910/4424 [01:05<00:08, 62.11it/s]

Epoch 9, Batch 3900, Loss: 1.3460

Epoch 9 Training:  91%|█████████ | 4008/4424 [01:07<00:06, 62.09it/s]

Epoch 9, Batch 4000, Loss: 1.3233

Epoch 9 Training:  93%|█████████▎| 4106/4424 [01:09<00:05, 61.99it/s]

Epoch 9, Batch 4100, Loss: 1.3465

Epoch 9 Training:  95%|█████████▌| 4211/4424 [01:10<00:03, 61.85it/s]

Epoch 9, Batch 4200, Loss: 1.3270

Epoch 9 Training:  97%|█████████▋| 4309/4424 [01:12<00:02, 56.15it/s]

Epoch 9, Batch 4300, Loss: 1.3480

Epoch 9 Training: 100%|█████████▉| 4407/4424 [01:14<00:00, 62.14it/s]

Epoch 9, Batch 4400, Loss: 1.3465

Epoch 9 Training: 100%|██████████| 4424/4424 [01:14<00:00, 59.39it/s]

Epoch 9 | Train Loss: 1.3424 | Train AUC: 0.7531 | MRR: 0.6545 | MAP: 0.6545 | nDCG@5: 0.7405 | nDCG@10: 0.7405

Epoch 9 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 321.50it/s]

Epoch 9 | Val Loss: 2.0184 | Val AUC: 0.7208 | MRR: 0.3211 | MAP: 0.2956 | nDCG@5: 0.2985 | nDCG@10: 0.3591

Epoch 10 Training:   2%|▏         | 107/4424 [00:01<01:12, 59.25it/s]

Epoch 10, Batch 100, Loss: 1.3470

Epoch 10 Training:   5%|▍         | 206/4424 [00:03<01:08, 61.85it/s]

Epoch 10, Batch 200, Loss: 1.3031

Epoch 10 Training:   7%|▋         | 311/4424 [00:05<01:08, 60.18it/s]

Epoch 10, Batch 300, Loss: 1.3245

Epoch 10 Training:   9%|▉         | 408/4424 [00:06<01:08, 58.72it/s]

Epoch 10, Batch 400, Loss: 1.3381

Epoch 10 Training:  12%|█▏        | 510/4424 [00:08<01:05, 59.33it/s]

Epoch 10, Batch 500, Loss: 1.3354

Epoch 10 Training:  14%|█▎        | 606/4424 [00:10<01:05, 58.66it/s]

Epoch 10, Batch 600, Loss: 1.3337

Epoch 10 Training:  16%|█▌        | 708/4424 [00:12<01:07, 55.41it/s]

Epoch 10, Batch 700, Loss: 1.3112

Epoch 10 Training:  18%|█▊        | 810/4424 [00:13<01:03, 56.94it/s]

Epoch 10, Batch 800, Loss: 1.3363

Epoch 10 Training:  20%|██        | 906/4424 [00:15<00:59, 59.18it/s]

Epoch 10, Batch 900, Loss: 1.3281

Epoch 10 Training:  23%|██▎       | 1008/4424 [00:17<00:57, 59.13it/s]

Epoch 10, Batch 1000, Loss: 1.3514

Epoch 10 Training:  25%|██▌       | 1110/4424 [00:18<00:55, 59.26it/s]

Epoch 10, Batch 1100, Loss: 1.3162

Epoch 10 Training:  27%|██▋       | 1206/4424 [00:20<00:54, 59.25it/s]

Epoch 10, Batch 1200, Loss: 1.3157

Epoch 10 Training:  30%|██▉       | 1308/4424 [00:22<00:52, 59.21it/s]

Epoch 10, Batch 1300, Loss: 1.3432

Epoch 10 Training:  32%|███▏      | 1410/4424 [00:24<00:52, 57.03it/s]

Epoch 10, Batch 1400, Loss: 1.3170

Epoch 10 Training:  34%|███▍      | 1506/4424 [00:25<00:49, 59.12it/s]

Epoch 10, Batch 1500, Loss: 1.3429

Epoch 10 Training:  36%|███▋      | 1607/4424 [00:27<00:45, 62.13it/s]

Epoch 10, Batch 1600, Loss: 1.3217

Epoch 10 Training:  39%|███▊      | 1712/4424 [00:29<00:43, 61.96it/s]

Epoch 10, Batch 1700, Loss: 1.3459

Epoch 10 Training:  41%|████      | 1810/4424 [00:30<00:42, 61.97it/s]

Epoch 10, Batch 1800, Loss: 1.3197

Epoch 10 Training:  43%|████▎     | 1908/4424 [00:32<00:41, 60.22it/s]

Epoch 10, Batch 1900, Loss: 1.3116

Epoch 10 Training:  45%|████▌     | 2006/4424 [00:34<00:39, 61.94it/s]

Epoch 10, Batch 2000, Loss: 1.3328

Epoch 10 Training:  48%|████▊     | 2111/4424 [00:36<00:37, 61.25it/s]

Epoch 10, Batch 2100, Loss: 1.3460

Epoch 10 Training:  50%|████▉     | 2209/4424 [00:37<00:35, 61.96it/s]

Epoch 10, Batch 2200, Loss: 1.3496

Epoch 10 Training:  52%|█████▏    | 2307/4424 [00:39<00:34, 62.05it/s]

Epoch 10, Batch 2300, Loss: 1.3562

Epoch 10 Training:  55%|█████▍    | 2412/4424 [00:40<00:32, 62.10it/s]

Epoch 10, Batch 2400, Loss: 1.3874

Epoch 10 Training:  57%|█████▋    | 2510/4424 [00:42<00:30, 62.08it/s]

Epoch 10, Batch 2500, Loss: 1.3633

Epoch 10 Training:  59%|█████▉    | 2608/4424 [00:44<00:29, 62.01it/s]

Epoch 10, Batch 2600, Loss: 1.3710

Epoch 10 Training:  61%|██████    | 2706/4424 [00:45<00:28, 61.33it/s]

Epoch 10, Batch 2700, Loss: 1.3500

Epoch 10 Training:  64%|██████▎   | 2811/4424 [00:47<00:26, 60.79it/s]

Epoch 10, Batch 2800, Loss: 1.3555

Epoch 10 Training:  66%|██████▌   | 2909/4424 [00:49<00:24, 60.91it/s]

Epoch 10, Batch 2900, Loss: 1.3333

Epoch 10 Training:  68%|██████▊   | 3008/4424 [00:50<00:24, 58.66it/s]

Epoch 10, Batch 3000, Loss: 1.3559

Epoch 10 Training:  70%|███████   | 3112/4424 [00:52<00:21, 60.31it/s]

Epoch 10, Batch 3100, Loss: 1.3461

Epoch 10 Training:  73%|███████▎  | 3210/4424 [00:54<00:27, 43.71it/s]

Epoch 10, Batch 3200, Loss: 1.3448

Epoch 10 Training:  75%|███████▍  | 3308/4424 [00:56<00:18, 61.53it/s]

Epoch 10, Batch 3300, Loss: 1.3454

Epoch 10 Training:  77%|███████▋  | 3406/4424 [00:57<00:16, 60.96it/s]

Epoch 10, Batch 3400, Loss: 1.3364

Epoch 10 Training:  79%|███████▉  | 3511/4424 [00:59<00:14, 62.16it/s]

Epoch 10, Batch 3500, Loss: 1.3492

Epoch 10 Training:  82%|████████▏ | 3609/4424 [01:01<00:13, 61.83it/s]

Epoch 10, Batch 3600, Loss: 1.3511

Epoch 10 Training:  84%|████████▍ | 3708/4424 [01:02<00:12, 59.22it/s]

Epoch 10, Batch 3700, Loss: 1.3551

Epoch 10 Training:  86%|████████▌ | 3810/4424 [01:04<00:10, 59.07it/s]

Epoch 10, Batch 3800, Loss: 1.3375

Epoch 10 Training:  88%|████████▊ | 3906/4424 [01:06<00:08, 59.26it/s]

Epoch 10, Batch 3900, Loss: 1.3495

Epoch 10 Training:  91%|█████████ | 4008/4424 [01:07<00:07, 59.17it/s]

Epoch 10, Batch 4000, Loss: 1.3696

Epoch 10 Training:  93%|█████████▎| 4110/4424 [01:09<00:05, 53.13it/s]

Epoch 10, Batch 4100, Loss: 1.3587

Epoch 10 Training:  95%|█████████▌| 4206/4424 [01:11<00:03, 59.04it/s]

Epoch 10, Batch 4200, Loss: 1.3493

Epoch 10 Training:  97%|█████████▋| 4308/4424 [01:13<00:01, 59.10it/s]

Epoch 10, Batch 4300, Loss: 1.3521

Epoch 10 Training: 100%|█████████▉| 4410/4424 [01:14<00:00, 62.02it/s]

Epoch 10, Batch 4400, Loss: 1.3204

Epoch 10 Training: 100%|██████████| 4424/4424 [01:15<00:00, 58.95it/s]

Epoch 10 | Train Loss: 1.3412 | Train AUC: 0.7534 | MRR: 0.6547 | MAP: 0.6547 | nDCG@5: 0.7407 | nDCG@10: 0.7407

Epoch 10 Validation: 100%|██████████| 31624/31624 [01:38<00:00, 321.29it/s]

Epoch 10 | Val Loss: 2.0061 | Val AUC: 0.7238 | MRR: 0.3241 | MAP: 0.2990 | nDCG@5: 0.3027 | nDCG@10: 0.3633
Finished Training

Baseline stored: {'config': 'nrms_hybrid_baseline', 'removed': 'ctr_norm_and_interaction_features', 'val_auc': np.float64(0.7246), 'val_mrr': np.float64(0.3278), 'val_map': np.float64(0.3019), 'val_ndcg5': np.float64(0.3075), 'val_ndcg10': np.float64(0.3653), 'best_epoch': 8}

#8. Evaluation

In [ ]:
model.eval()

test_all_labels = []
test_all_scores = []
test_loss = 0.0

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Testing"):
        candidate_inputs = {k: v.to(device) for k, v in batch["candidate_inputs"].items()}
        history_inputs = {k: v.to(device) for k, v in batch["history_inputs"].items()}
        user_num = batch["user_numerical"].to(device)
        user_cat = {k: v.to(device) for k, v in batch["user_categorical"].items()}
        topic = batch["topic"].to(device)
        context_features = batch["context_features"].to(device)
        labels = batch["labels"].to(device)   # [B, C]

        scores = model(
            candidate_inputs=candidate_inputs,
            history_inputs=history_inputs,
            user_numerical_dense=user_num,
            user_categorical_input=user_cat,
            topic_embed=topic,
            context_features=context_features,
        )   # [B, C]

        # optional CE loss for test
        if labels.sum(dim=1).eq(1).all():
            target_idx = labels.argmax(dim=1)
            test_loss += F.cross_entropy(scores, target_idx).item()

        probs = torch.softmax(scores, dim=1)

        test_all_scores.extend(probs.cpu().numpy().tolist())
        test_all_labels.extend(labels.cpu().numpy().tolist())

avg_test_loss = test_loss / len(test_loader)

test_mrr, test_map, test_ndcg5, test_ndcg10 = calculate_ranking_metrics(
    test_all_labels,
    test_all_scores
)

flat_test_labels = [label for row in test_all_labels for label in row]
flat_test_scores = [score for row in test_all_scores for score in row]

if len(np.unique(flat_test_labels)) > 1:
    test_auc = roc_auc_score(flat_test_labels, flat_test_scores)
else:
    test_auc = 0.0

print(
    f"Test Loss: {avg_test_loss:.4f} | "
    f"Test AUC: {test_auc:.4f} | "
    f"Test MRR: {test_mrr:.4f} | "
    f"Test MAP: {test_map:.4f} | "
    f"Test nDCG@5: {test_ndcg5:.4f} | "
    f"Test nDCG@10: {test_ndcg10:.4f}"
)

Testing: 100%|██████████| 30270/30270 [01:34<00:00, 319.51it/s]

Test Loss: 2.0387 | Test AUC: 0.7036 | Test MRR: 0.3013 | Test MAP: 0.2745 | Test nDCG@5: 0.2733 | Test nDCG@10: 0.3337